import { render,screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'

const emptyPage={items:[],page:1,page_size:100,total:0,has_next:false}
afterEach(()=>{sessionStorage.clear();vi.unstubAllGlobals()})

it('keeps existing M1-M4 navigation while grouping the new Editorial workspace',async()=>{vi.stubGlobal('fetch',vi.fn(async(raw:string|URL|Request)=>{const url=String(raw);if(url.includes('/workbench/overview'))return Response.json({generated_at:'2026-08-09T10:00:00Z',active_event_count:0,lifecycle_counts:{emerging:0,growing:0,stable:0,declining:0,resolved:0},recent_new_event_count_24h:0,recent_updated_event_count_24h:0,events_with_evidence_count:0,open_unknown_count:0,high_risk_event_count:0,artifact_counts:{trend_snapshots:0,editorial_scores:0,event_cards:0,editorial_packs:0,drafts:0},collection_health:{failed_runs_24h:0,paused_risk_runs_24h:0,open_risk_events:0,paused_accounts:0,checkpoint_count:0},production_ai_provider_validation:'NOT_TESTED'});if(url.includes('/connector-definitions'))return Response.json(emptyPage);return Response.json(emptyPage)}));render(<App/>);expect(await screen.findByText('今日重点关注')).toBeInTheDocument();for(const label of ['今日总览','事件','信源','采集任务','运行记录','检查点','账号 / 风险','连接器定义','连接器实例','AI 服务商','AI 路由','AI 预算','AI 调用记录'])expect(screen.getAllByRole('button',{name:label}).length).toBeGreaterThan(0);await userEvent.click(screen.getByRole('button',{name:'连接器定义'}));expect(await screen.findByText('暂无已注册的连接器定义')).toBeInTheDocument()})

it('stores session config only in sessionStorage and communicates Actor requirement before writes',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json({generated_at:'2026-08-09T10:00:00Z',active_event_count:0,lifecycle_counts:{emerging:0,growing:0,stable:0,declining:0,resolved:0},recent_new_event_count_24h:0,recent_updated_event_count_24h:0,events_with_evidence_count:0,open_unknown_count:0,high_risk_event_count:0,artifact_counts:{trend_snapshots:0,editorial_scores:0,event_cards:0,editorial_packs:0,drafts:0},collection_health:{failed_runs_24h:0,paused_risk_runs_24h:0,open_risk_events:0,paused_accounts:0,checkpoint_count:0},production_ai_provider_validation:'NOT_TESTED'})));render(<App/>);await screen.findByText('今日重点关注');await userEvent.click(screen.getByText('会话与编辑身份'));await userEvent.type(screen.getByLabelText('管理员 Token'),'token-only');await userEvent.click(screen.getByRole('button',{name:'应用会话配置'}));expect(screen.getByText(/请配置执行者 ID/)).toBeInTheDocument();expect(sessionStorage.length).toBe(1);expect(localStorage.length).toBe(0)})
