import { render,screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'

const emptyPage={items:[],page:1,page_size:100,total:0,has_next:false}
afterEach(()=>{sessionStorage.clear();vi.unstubAllGlobals()})

it('keeps existing M1-M4 navigation while grouping the new Editorial workspace',async()=>{vi.stubGlobal('fetch',vi.fn(async(raw:string|URL|Request)=>{const url=String(raw);if(url.includes('/workbench/overview'))return Response.json({generated_at:'2026-08-09T10:00:00Z',active_event_count:0,lifecycle_counts:{emerging:0,growing:0,stable:0,declining:0,resolved:0},recent_new_event_count_24h:0,recent_updated_event_count_24h:0,events_with_evidence_count:0,open_unknown_count:0,high_risk_event_count:0,artifact_counts:{trend_snapshots:0,editorial_scores:0,event_cards:0,editorial_packs:0,drafts:0},collection_health:{failed_runs_24h:0,paused_risk_runs_24h:0,open_risk_events:0,paused_accounts:0,checkpoint_count:0},production_ai_provider_validation:'NOT_TESTED'});if(url.includes('/connector-definitions'))return Response.json(emptyPage);return Response.json(emptyPage)}));render(<App/>);expect(await screen.findByText(/M5-B operational overview/i)).toBeInTheDocument();for(const label of ['Overview','Events','Sources','Schedules','Runs','Checkpoints','Accounts / Risk','Definitions','Instances','AI Providers','AI Routes','AI Budgets','AI Invocations'])expect(screen.getAllByRole('button',{name:label}).length).toBeGreaterThan(0);await userEvent.click(screen.getByRole('button',{name:'Definitions'}));expect(await screen.findByText('暂无数据')).toBeInTheDocument()})

it('stores session config only in sessionStorage and communicates Actor requirement before writes',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json({generated_at:'2026-08-09T10:00:00Z',active_event_count:0,lifecycle_counts:{emerging:0,growing:0,stable:0,declining:0,resolved:0},recent_new_event_count_24h:0,recent_updated_event_count_24h:0,events_with_evidence_count:0,open_unknown_count:0,high_risk_event_count:0,artifact_counts:{trend_snapshots:0,editorial_scores:0,event_cards:0,editorial_packs:0,drafts:0},collection_health:{failed_runs_24h:0,paused_risk_runs_24h:0,open_risk_events:0,paused_accounts:0,checkpoint_count:0},production_ai_provider_validation:'NOT_TESTED'})));render(<App/>);await screen.findByText(/M5-B operational overview/i);await userEvent.type(screen.getByLabelText('Admin Token'),'token-only');await userEvent.click(screen.getByRole('button',{name:'应用会话配置'}));expect(screen.getByText(/Configure Actor ID/)).toBeInTheDocument();expect(sessionStorage.length).toBe(1);expect(localStorage.length).toBe(0)})
