import { useCallback,useEffect,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,JsonSummary,RiskBadge,SectionState,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EditorialPack,EventCard } from '../../workbenchTypes'
import { editorialFormatLabel,sourceTypeLabel } from '../../uiLabels'

export function EventCardPackSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[cards,setCards]=useState<EventCard[]>([]);const[packs,setPacks]=useState<EditorialPack[]>([]);const[cardId,setCardId]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[c,p]=await Promise.all([api.cards(eventId),api.packs(eventId)]);setCards(c);setPacks(p);setCardId(x=>x||c[0]?.id||'')}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 const mutate=async(fn:()=>Promise<unknown>)=>{try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}}
 const latest=cards[0]||null,latestPack=packs[0]||null
 return <div className="wb-two-col align-start"><Panel title="Event Card"><SectionState loading={loading} error={error}>{latest?<CardView card={latest}/>:<Empty text="暂无 Event Card"/>}</SectionState><div className="actions"><button className="primary" disabled={!canWrite} title={!canWrite?'配置执行者 ID 后才能操作；已合并事件只读':''} onClick={()=>void mutate(()=>api.createCard(eventId,null))}>创建新 Card</button></div><details><summary>Card 版本历史（{cards.length}）</summary>{cards.map(c=><CardView key={c.id} card={c}/>)}</details></Panel>
  <Panel title="Editorial Pack"><SectionState loading={loading} error={error}>{latestPack?<PackView pack={latestPack}/>:<Empty text="暂无 Editorial Pack"/>}</SectionState><div className="inline-form"><label>基于 Event Card<select value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">选择 Card</option>{cards.map(c=><option value={c.id} key={c.id}>{c.card_version} · {fmt(c.created_at)}</option>)}</select></label><button className="primary" disabled={!canWrite||!cardId} onClick={()=>void mutate(()=>api.createPack(eventId,cardId))}>创建 Editorial Pack</button></div><details><summary>Pack 版本历史（{packs.length}）</summary>{packs.map(p=><PackView key={p.id} pack={p}/>)}</details></Panel></div>
}
function CardView({card}:{card:EventCard}){return <article className="artifact-card"><div className="badges"><Badge tone="info">{card.card_version}</Badge><RiskBadge value={card.risk_level}/><Badge>{editorialFormatLabel[card.recommended_format]||card.recommended_format}</Badge><Badge>{sourceTypeLabel[card.generated_by]||card.generated_by}</Badge></div><h3>{card.title}</h3><p>{card.concise_summary}</p><div className="provenance"><span>创建于 {fmt(card.created_at)}</span><span>输入摘要 {card.input_hash.slice(0,12)}…</span><span>证据快照 {card.evidence_snapshot_hash.slice(0,12)}…</span><span>趋势快照 {card.trend_snapshot_id||'暂无'}</span><span>评分 {card.editorial_score_id}</span></div><details><summary>事实主张分组、时间线与信源摘要</summary><div className="claim-id-grid"><span>已确认 {card.confirmed_claim_ids.length}</span><span>核验中 {card.investigating_claim_ids.length}</span><span>单一信源 {card.single_source_claim_ids.length}</span><span>存在争议 {card.disputed_claim_ids.length}</span><span>已证伪 {card.false_claim_ids.length}</span><span>待确认点 {card.unknown_ids.length}</span></div><JsonSummary value={{timeline:card.timeline,source_summary:card.source_summary,effective_assessment:card.effective_assessment}}/></details></article>}
function PackView({pack}:{pack:EditorialPack}){return <article className="artifact-card"><div className="badges"><Badge tone="info">{pack.pack_version}</Badge><Badge>{editorialFormatLabel[pack.recommended_format]||pack.recommended_format}</Badge></div><div className="provenance"><span>创建于 {fmt(pack.created_at)}</span><span>Card {pack.event_card_id}</span><span>输入摘要 {pack.input_hash.slice(0,12)}…</span></div><Section name="建议角度" value={pack.suggested_angles}/><Section name="信源材料" value={pack.source_items}/><Section name="时间线" value={pack.timeline_items}/>{pack.material_items.length?<Section name="媒体素材" value={pack.material_items}/>:<div className="unavailable">暂无媒体元数据</div>}<Section name="风险提示" value={pack.warnings}/><Section name="待确认点" value={pack.unknown_items}/><Section name="事实主张引用" value={pack.claim_references}/></article>}
function Section({name,value}:{name:string;value:Array<Record<string,unknown>>}){return <details><summary>{name}（{value.length}）</summary>{value.length?<JsonSummary value={value}/>:<Empty text={`暂无${name}`}/>}</details>}
