import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,RiskBadge,SectionState,Unavailable,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EditorialFormat,EditorialRisk,EditorialScore,EffectiveEditorialResponse,ScoreRunResponse,TrendSnapshot } from '../../workbenchTypes'

const dims=['emotion','information_gap','visual_value','user_relevance','discussion','novelty','extendability'] as const
type Dim=typeof dims[number]
const formats:EditorialFormat[]=['daily_compilation','quick_explainer','fact_check','deep_dive','entertainment','consumer_safety']
const risks:EditorialRisk[]=['R0','R1','R2','R3','R4']
const toLocal=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)}

export function EventTrendScoreSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[trend,setTrend]=useState<TrendSnapshot|null>(null);const[scores,setScores]=useState<EditorialScore[]>([]);const[effective,setEffective]=useState<EffectiveEditorialResponse|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[preview,setPreview]=useState<ScoreRunResponse|null>(null)
 const[now]=useState(()=>new Date());const[start,setStart]=useState(()=>toLocal(new Date(now.getTime()-24*3600*1000)));const[end,setEnd]=useState(()=>toLocal(now));const[manual,setManual]=useState<Record<Dim,number>>(()=>Object.fromEntries(dims.map(d=>[d,50])) as Record<Dim,number>);const[manualRisk,setManualRisk]=useState<EditorialRisk>('R1');const[manualFormat,setManualFormat]=useState<EditorialFormat>('quick_explainer');const[manualReason,setManualReason]=useState('');const[overrideField,setOverrideField]=useState<Dim|'risk_level'|'recommended_format'>('emotion');const[overrideValue,setOverrideValue]=useState('50');const[overrideReason,setOverrideReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[t,s,e]=await Promise.all([api.event(eventId).then(v=>v.latest_trend),api.scores(eventId),api.effectiveScore(eventId)]);setTrend(t);setScores(s);setEffective(e)}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 const mutate=async(fn:()=>Promise<unknown>)=>{try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}}
 const runScore=async(apply:boolean)=>{if(!trend)return;try{setError(null);const r=apply?await api.applyScore(eventId,trend.id):await api.previewScore(eventId,trend.id);setPreview(r);if(apply){await load();onChanged()}}catch(e){setError(FriendlyError(e))}}
 const baseId=effective?.effective_base_score_id;const effectiveValues=effective?.effective_values
 const unavailable=useMemo(()=>{const raw=trend?.component_metrics.unavailable_reasons;return raw&&typeof raw==='object'?raw as Record<string,unknown>:{}},[trend])
 const overridePayload=()=>{let value:unknown=overrideValue;if(dims.includes(overrideField as Dim))value=Math.max(0,Math.min(100,Number(overrideValue)));return{[overrideField]:value,reason:overrideReason}}
 return <div className="wb-two-col align-start"><Panel title="Trend"><SectionState loading={loading} error={error}>{trend?<><div className="trend-grid"><Value name="window" value={`${fmt(trend.window_start_at)} → ${fmt(trend.window_end_at)}`}/><Value name="signal_count" value={trend.signal_count}/><Value name="new_signal_count" value={trend.new_signal_count}/><Value name="source_count" value={trend.source_count}/><Value name="platform_count" value={trend.platform_count}/><Feature name="signal_velocity" value={trend.signal_velocity} available={trend.feature_availability.signal_velocity}/><Feature name="interaction_velocity" value={trend.interaction_velocity} available={trend.feature_availability.interaction_velocity} reason={str(unavailable.interaction_velocity)}/><Feature name="semantic_novelty" value={trend.semantic_novelty} available={trend.feature_availability.semantic_novelty} reason={str(unavailable.semantic_novelty)}/><Feature name="cn_gap" value={trend.cn_gap} available={trend.feature_availability.cn_gap} reason={str(unavailable.cn_gap)}/><Feature name="media_availability" value={null} available={trend.feature_availability.media_availability} reason={str(unavailable.media_availability)}/><Value name="cross_source" value={trend.cross_source?'Yes':'No'}/><Value name="cross_platform" value={trend.cross_platform?'Yes':'No'}/><Feature name="update_value" value={trend.update_value} available={trend.feature_availability.update_value}/></div></>:<Empty text="Trend not calculated"/>}</SectionState>
  <div className="action-box"><h3>Recalculate Trend</h3><p>No automatic recalculation occurs on page load.</p><div className="inline-form"><label>Window start<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Window end<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button disabled={!canWrite||!start||!end} title={!canWrite?'Configure Actor ID or use an active Event':''} onClick={()=>void mutate(()=>api.calculateTrend(eventId,new Date(start).toISOString(),new Date(end).toISOString()))}>Calculate Trend</button></div></div>
 </Panel><Panel title="Editorial Score"><SectionState loading={loading} error={null}><div className="score-comparison"><ScoreBlock title="Original AI Score" score={effective?.latest_ai_score}/><ScoreBlock title="Latest Human Score" score={effective?.latest_human_score}/><EffectiveBlock values={effectiveValues} overridden={Boolean(effective?.applied_overrides.length)}/></div>{effective?.applied_overrides.length?<div className="override-history"><h4>Human Overrides</h4>{effective.applied_overrides.map(o=><div key={o.id}><Badge tone="warn">Human Override Applied</Badge> {Object.keys(o.overridden_fields).join(', ')} · {o.actor} · {o.reason} · {fmt(o.created_at)}</div>)}</div>:null}</SectionState>
  <div className="action-box"><h3>AI Score</h3><p className="warning-text">Preview and Apply are explicit AI calls. In a real Provider environment both may consume tokens, cost and budget.</p><div className="actions"><button disabled={!canWrite||!trend} onClick={()=>void runScore(false)}>Preview AI Score</button><button disabled={!canWrite||!trend} onClick={()=>void runScore(true)}>Apply AI Score</button></div>{preview&&<ScorePreview value={preview}/>}</div>
  <div className="action-box"><h3>Human Score</h3><div className="dimension-inputs">{dims.map(d=><label key={d}>{d}<input type="number" min="0" max="100" value={manual[d]} onChange={e=>setManual({...manual,[d]:Number(e.target.value)})}/></label>)}</div><div className="inline-form"><label>Risk<select value={manualRisk} onChange={e=>setManualRisk(e.target.value as EditorialRisk)}>{risks.map(r=><option key={r}>{r}</option>)}</select></label><label>Format<select value={manualFormat} onChange={e=>setManualFormat(e.target.value as EditorialFormat)}>{formats.map(f=><option key={f}>{f}</option>)}</select></label><label>Reason<input value={manualReason} onChange={e=>setManualReason(e.target.value)}/></label><button disabled={!canWrite||!manualReason.trim()} onClick={()=>void mutate(()=>api.manualScore(eventId,{trend_snapshot_id:trend?.id||null,...manual,risk_level:manualRisk,recommended_format:manualFormat,reason:manualReason}))}>Create Human Score</button></div></div>
  <div className="action-box"><h3>Human Override</h3><p>Original AI score remains visible after override.</p><div className="inline-form"><label>Field<select value={overrideField} onChange={e=>{const v=e.target.value as typeof overrideField;setOverrideField(v);setOverrideValue(v==='risk_level'?'R2':v==='recommended_format'?'quick_explainer':'50')}}>{[...dims,'risk_level','recommended_format'].map(f=><option key={f}>{f}</option>)}</select></label>{overrideField==='risk_level'?<label>Value<select value={overrideValue} onChange={e=>setOverrideValue(e.target.value)}>{risks.map(r=><option key={r}>{r}</option>)}</select></label>:overrideField==='recommended_format'?<label>Value<select value={overrideValue} onChange={e=>setOverrideValue(e.target.value)}>{formats.map(f=><option key={f}>{f}</option>)}</select></label>:<label>Value<input type="number" min="0" max="100" value={overrideValue} onChange={e=>setOverrideValue(e.target.value)}/></label>}<label>Reason<input value={overrideReason} onChange={e=>setOverrideReason(e.target.value)}/></label><button disabled={!canWrite||!baseId||!overrideReason.trim()} onClick={()=>void mutate(()=>api.overrideScore(eventId,baseId!,overridePayload()))}>Apply Override</button></div></div>
  <details><summary>Score history ({scores.length})</summary>{scores.map(s=><ScoreBlock key={s.id} title={`${s.source_type.toUpperCase()} · ${fmt(s.created_at)}`} score={s}/>)}</details>
 </Panel></div>
}
function str(v:unknown){return typeof v==='string'?v:undefined}
function Value({name,value}:{name:string;value:string|number}){return <div className="trend-value"><small>{name}</small><strong>{value}</strong></div>}
function Feature({name,value,available,reason}:{name:string;value:number|null;available:boolean|undefined;reason?:string}){return <div className="trend-value"><small>{name}</small><strong>{available===false||value===null?<Unavailable reason={reason}/>:value}</strong></div>}
function ScoreBlock({title,score}:{title:string;score:EditorialScore|null|undefined}){return <section className="score-block"><h4>{title}</h4>{!score?<Empty text="Not scored"/>:<><div className="badges"><Badge tone={score.source_type==='human'?'ok':'info'}>{score.source_type.toUpperCase()}</Badge><RiskBadge value={score.risk_level}/><Badge>{score.recommended_format}</Badge></div><div className="score-dims">{dims.map(d=><span key={d}><small>{d}</small><strong>{score[d]}</strong></span>)}<span><small>traffic_total</small><strong>{score.traffic_total.toFixed(1)}</strong></span></div><p>{score.model_reason||'No model reason'}</p>{score.ai_invocation_id&&<small>Invocation ID: {score.ai_invocation_id}</small>}{score.source_reason&&<small>Human reason: {score.source_reason}</small>}</>}</section>}
function EffectiveBlock({values,overridden}:{values:Record<string,unknown>|null|undefined;overridden:boolean}){return <section className="score-block effective"><h4>Effective Score {overridden&&<Badge tone="warn">Human Override Applied</Badge>}</h4>{!values?<Empty text="Not scored"/>:<><div className="badges"><RiskBadge value={(values.risk_level as EditorialRisk)||'R0'}/><Badge>{String(values.recommended_format||'Unavailable')}</Badge></div><div className="score-dims">{dims.map(d=><span key={d}><small>{d}</small><strong>{String(values[d]??'Unavailable')}</strong></span>)}<span><small>traffic_total</small><strong>{String(values.traffic_total??'Unavailable')}</strong></span></div></>}</section>}
function ScorePreview({value}:{value:ScoreRunResponse}){return <div className="preview-box"><Badge tone="info">PREVIEW · not saved</Badge><RiskBadge value={value.risk_level}/><strong> traffic {value.traffic_total.toFixed(1)}</strong><div className="score-dims">{dims.map(d=><span key={d}><small>{d}</small><strong>{value[d]}</strong></span>)}</div><p>{value.model_reason}</p>{value.ai_invocation_id&&<small>Invocation ID: {value.ai_invocation_id}</small>}</div>}
