import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,EvidenceBadge,FriendlyError,SafeLink,SectionState,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EvidenceClaim,EvidenceState,EventEvidence,EventUnknown } from '../../workbenchTypes'

const states:EvidenceState[]=['confirmed','investigating','single_source','disputed','false']
export function EventEvidenceSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[data,setData]=useState<EventEvidence|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[newUnknown,setNewUnknown]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api.evidence(eventId))}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId])
 useEffect(()=>{void load()},[load])
 const mutate=async(fn:()=>Promise<unknown>)=>{try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}}
 const grouped=useMemo(()=>Object.fromEntries(states.map(s=>[s,data?.claims.filter(c=>c.verification_state===s)||[]])) as Record<EvidenceState,EvidenceClaim[]>,[data])
 return <Panel title="Evidence / Claims / Unknowns" actions={<button onClick={()=>void load()}>Refresh</button>}>
  <div className="notice">Verification state is authoritative. <strong>single_source is not confirmed</strong>; Unknowns are questions, never Facts. Backend verification rules remain the final gate.</div>
  <SectionState loading={loading} error={error} empty={!data}>{data&&<>
   {states.map(state=><section className="claim-group" key={state}><h3><EvidenceBadge value={state}/> <span>{grouped[state].length}</span></h3>{grouped[state].length===0?<Empty text={`No ${state} claims`}/>:grouped[state].map(claim=><ClaimCard key={claim.id} claim={claim} canWrite={canWrite} onVerify={(s,r)=>mutate(()=>api.verifyClaim(eventId,claim.id,s,r))} onNote={note=>mutate(()=>api.updateClaimNote(eventId,claim.id,note))} onAttach={(sid,role)=>mutate(()=>api.attachClaimSource(eventId,claim.id,sid,role))} onRemove={sid=>mutate(()=>api.removeClaimSource(eventId,claim.id,sid))}/>)}</section>)}
   <section className="unknown-group"><h3>Unknowns</h3><div className="badges"><Badge tone="warn">open {data.unknowns.filter(x=>x.status==='open').length}</Badge><Badge>resolved {data.unknowns.filter(x=>x.status==='resolved').length}</Badge><Badge>dismissed {data.unknowns.filter(x=>x.status==='dismissed').length}</Badge></div>
    <div className="unknown-list">{data.unknowns.map(u=><UnknownCard key={u.id} item={u} canWrite={canWrite} update={(status,note)=>mutate(()=>api.updateUnknown(eventId,u.id,status,note))}/>)}</div>
    <div className="inline-form"><label>Human Unknown<input value={newUnknown} onChange={e=>setNewUnknown(e.target.value)} placeholder="Unresolved question"/></label><button disabled={!canWrite||!newUnknown.trim()} title={!canWrite?'Configure Actor ID or use an active Event':''} onClick={()=>void mutate(async()=>{await api.createUnknown(eventId,newUnknown.trim());setNewUnknown('')})}>Add Unknown</button></div>
   </section>
  </>}</SectionState>
 </Panel>
}

function ClaimCard({claim,canWrite,onVerify,onNote,onAttach,onRemove}:{claim:EvidenceClaim;canWrite:boolean;onVerify:(s:EvidenceState,r:string)=>Promise<void>;onNote:(n:string)=>Promise<void>;onAttach:(id:string,role:'supporting'|'contradicting')=>Promise<void>;onRemove:(id:string)=>Promise<void>}){
 const[open,setOpen]=useState(false);const[state,setState]=useState<EvidenceState>(claim.verification_state);const[reason,setReason]=useState('');const[note,setNote]=useState(claim.editor_note||'');const[signalId,setSignalId]=useState('');const[role,setRole]=useState<'supporting'|'contradicting'>('supporting');const support=claim.sources.filter(s=>s.role==='supporting').length,against=claim.sources.filter(s=>s.role==='contradicting').length
 return <article className="claim-card"><div className="claim-head"><div><EvidenceBadge value={claim.verification_state}/> <Badge>{claim.claim_type}</Badge> <Badge tone={claim.created_by_type==='human'?'ok':'info'}>{claim.created_by_type.toUpperCase()}</Badge></div><button aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Hide sources':'Sources & actions'}</button></div><p className="claim-text">{claim.claim_text}</p><div className="claim-meta"><span>supporting {support}</span><span>contradicting {against}</span><span>confidence {claim.extraction_confidence??'Unavailable'}</span><span>actor {claim.created_by_actor||'AI provenance'}</span><span>{fmt(claim.updated_at)}</span></div>{claim.editor_note&&<p className="editor-note">Editor note: {claim.editor_note}</p>}
  {open&&<div className="claim-detail"><div className="source-columns"><div><h4>Supporting</h4>{claim.sources.filter(s=>s.role==='supporting').map(s=><SourceItem key={s.signal_id} source={s} canWrite={canWrite} remove={()=>onRemove(s.signal_id)}/>)}</div><div><h4>Contradicting</h4>{claim.sources.filter(s=>s.role==='contradicting').map(s=><SourceItem key={s.signal_id} source={s} canWrite={canWrite} remove={()=>onRemove(s.signal_id)}/>)}</div></div>
   <div className="inline-form"><label>Verification<select value={state} onChange={e=>setState(e.target.value as EvidenceState)}>{states.map(v=><option key={v}>{v}</option>)}</select></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required human reason"/></label><button disabled={!canWrite||!reason.trim()} title={!canWrite?'Configure Actor ID or use an active Event':''} onClick={()=>void onVerify(state,reason)}>Verify</button></div>
   <div className="inline-form"><label>Editor note<input value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!canWrite||!note.trim()} onClick={()=>void onNote(note)}>Save note</button></div>
   <div className="inline-form"><label>Signal ID<input value={signalId} onChange={e=>setSignalId(e.target.value)} placeholder="Existing RawSignal UUID"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as 'supporting'|'contradicting')}><option>supporting</option><option>contradicting</option></select></label><button disabled={!canWrite||!signalId.trim()} onClick={()=>void onAttach(signalId.trim(),role)}>Attach source</button></div>
  </div>}
 </article>
}
function SourceItem({source,canWrite,remove}:{source:EvidenceClaim['sources'][number];canWrite:boolean;remove:()=>Promise<void>}){return <div className="source-item"><SafeLink url={source.original_url}>{source.title||source.original_url}</SafeLink><small>{source.platform} · {source.author_name||'Unknown author'} · {fmt(source.published_at||source.collected_at)}</small><button disabled={!canWrite} onClick={()=>void remove()}>Remove</button></div>}
function UnknownCard({item,canWrite,update}:{item:EventUnknown;canWrite:boolean;update:(s:'resolved'|'dismissed',n:string)=>Promise<void>}){const[note,setNote]=useState(item.resolution_note||'');return <article className={`unknown-card ${item.status==='open'?'open':''}`}><div><Badge tone={item.status==='open'?'warn':'muted'}>{item.status}</Badge> <Badge>{item.source_type.toUpperCase()}</Badge></div><p>{item.unknown_text}</p>{item.resolution_note&&<small>Resolution: {item.resolution_note}</small>}{item.status==='open'&&<div className="inline-form"><label>Resolution note<input value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!canWrite||!note.trim()} onClick={()=>void update('resolved',note)}>Resolve</button><button disabled={!canWrite||!note.trim()} onClick={()=>void update('dismissed',note)}>Dismiss</button></div>}</article>}
