import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,JsonSummary,RiskBadge,SectionState } from '../workbench'
import { ClaimReferencePicker } from './ClaimReferencePicker'
import { DraftChainView } from './DraftChainView'
import type { DraftRefInput,WorkbenchApi } from '../../workbenchApi'
import type { CitationUsage,DraftDetail,DraftGenerationResponse,DraftType,EditorialDraft,EditorialPack,EventCard,EventEvidence } from '../../workbenchTypes'

export function EventDraftsSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[drafts,setDrafts]=useState<EditorialDraft[]>([]),[cards,setCards]=useState<EventCard[]>([]),[packs,setPacks]=useState<EditorialPack[]>([]);const[evidence,setEvidence]=useState<EventEvidence|null>(null);const[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const[cardId,setCardId]=useState(''),[packId,setPackId]=useState(''),[draftType,setDraftType]=useState<DraftType>('standard_90s'),[approval,setApproval]=useState(''),[preview,setPreview]=useState<DraftGenerationResponse|null>(null),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<DraftDetail|null>(null);const[body,setBody]=useState(''),[reason,setReason]=useState(''),[refs,setRefs]=useState<Record<string,CitationUsage>>({}),[changeNote,setChangeNote]=useState(''),[markdown,setMarkdown]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[d,c,p,e]=await Promise.all([api.drafts(eventId),api.cards(eventId),api.packs(eventId),api.evidence(eventId)]);setDrafts(d);setCards(c);setPacks(p);setEvidence(e);setCardId(v=>v||c[0]?.id||'');setPackId(v=>v||p[0]?.id||'')}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 const card=cards.find(c=>c.id===cardId)||null,pack=packs.find(p=>p.id===packId)||null,risk=card?.risk_level;const blocked=risk==='R4'&&pack?.recommended_format!=='fact_check',needsApproval=risk==='R3'&&!approval.trim();const selectedRefs=useMemo<DraftRefInput[]>(()=>Object.entries(refs).map(([claim_id,usage])=>({claim_id,usage,section_key:'main'})),[refs]);const latest=detail?Math.max(...detail.version_chain.map(v=>v.draft_version)):0,isLatest=detail?.draft.draft_version===latest
 const mutate=async(fn:()=>Promise<unknown>)=>{try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}}
 const generate=async(apply:boolean)=>{if(!cardId||!packId)return;try{const payload={event_card_id:cardId,editorial_pack_id:packId,draft_type:draftType,...(approval.trim()?{risk_approval_reason:approval.trim()}: {})};const r=apply?await api.applyDraft(eventId,payload):await api.previewDraft(eventId,payload);setPreview(r);if(apply){await load();onChanged()}}catch(e){setError(FriendlyError(e))}}
 const open=async(id:string)=>{setSelected(id);try{const d=await api.draft(eventId,id);setDetail(d);setBody(d.draft.body);setRefs(Object.fromEntries(d.claim_references.map(r=>[r.claim_id,r.usage])))}catch(e){setError(FriendlyError(e))}}
 return <Panel title="Drafts / Revisions / Markdown Export"><SectionState loading={loading} error={error}>{!loading&&<>
  <div className="draft-context"><label>Event Card<select value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">Select</option>{cards.map(c=><option key={c.id} value={c.id}>{c.card_version}</option>)}</select></label><label>Editorial Pack<select value={packId} onChange={e=>setPackId(e.target.value)}><option value="">Select</option>{packs.map(p=><option key={p.id} value={p.id}>{p.pack_version} · {p.recommended_format}</option>)}</select></label><label>Draft type<select value={draftType} onChange={e=>setDraftType(e.target.value as DraftType)}><option value="short_30s">short_30s · 30s</option><option value="standard_90s">standard_90s · 90s</option><option value="deep_180s">deep_180s · 180s</option></select></label><strong>Format: {pack?.recommended_format||'Unavailable'}</strong>{risk&&<RiskBadge value={risk}/>}</div>
  <div className="action-box"><h3>AI Draft Preview / Apply</h3><p className="warning-text">Preview is an explicit AI call and may consume tokens, cost and budget. It does not save a formal Draft.</p>{risk==='R3'&&<label>R3 Human approval reason<input aria-label="R3 Human approval reason" value={approval} onChange={e=>setApproval(e.target.value)}/></label>}{blocked&&<div className="error-banner">R4 cannot generate a non-fact_check Draft.</div>}<div className="actions"><button disabled={!canWrite||!cardId||!packId||blocked||needsApproval} title={!canWrite?'Configure Actor ID or use an active Event':needsApproval?'R3 requires Human approval reason':''} onClick={()=>void generate(false)}>Preview Draft</button><button disabled={!canWrite||!cardId||!packId||blocked||needsApproval} onClick={()=>void generate(true)}>Generate / Apply</button></div>{preview&&<div className="preview-box"><Badge tone="info">{preview.mode.toUpperCase()} · {preview.draft?'saved':'not saved'}</Badge>{preview.ai_invocation_id&&<p>Invocation ID: {preview.ai_invocation_id}</p>}{preview.candidate&&<JsonSummary value={preview.candidate}/>}</div>}</div>
  <div className="wb-two-col align-start"><div><h3>Draft chains</h3><DraftChainView drafts={drafts} selectedId={selected} onSelect={id=>void open(id)}/></div><div>{detail?<DraftReader detail={detail}/>:<Empty text="Select a Draft version"/>}</div></div>
  <div className="action-box"><h3>Human Draft / Revision</h3><p>Claim state and allowed usage are shown before editing. The backend remains authoritative.</p><ClaimReferencePicker claims={evidence?.claims||[]} refs={refs} onChange={setRefs}/><label>Reason / change note<input value={reason||changeNote} onChange={e=>detail?setChangeNote(e.target.value):setReason(e.target.value)}/></label><label>Body<textarea value={body} onChange={e=>setBody(e.target.value)} rows={9}/></label>{detail?<><p>Parent v{detail.draft.draft_version}. Old versions remain visible.</p>{!isLatest&&<div className="error-banner">Selected version is no longer latest; refresh/select latest before revising.</div>}<button disabled={!canWrite||!isLatest||!changeNote.trim()||!body.trim()||!selectedRefs.length} onClick={()=>void mutate(async()=>{try{await api.revise(eventId,detail.draft.id,{change_note:changeNote,body,references:selectedRefs,title:detail.draft.title||undefined})}catch(e){await load();throw e}})}>Create Revision</button></>:<button disabled={!canWrite||!cardId||!packId||!reason.trim()||!body.trim()||!selectedRefs.length} onClick={()=>void mutate(()=>api.humanDraft(eventId,{event_card_id:cardId,editorial_pack_id:packId,draft_type:draftType,reason,body,references:selectedRefs}))}>Create Human Draft</button>}</div>
  <div className="action-box"><h3>Markdown Export</h3><p>Calls the deterministic M4-D exporter. No AI is used and the browser does not rebuild Markdown.</p><button disabled={!packId} onClick={()=>void api.exportMarkdown(eventId,packId,selected||undefined).then(setMarkdown).catch(e=>setError(FriendlyError(e)))}>Export Markdown</button>{markdown&&<pre className="markdown-view">{markdown}</pre>}</div>
 </>}</SectionState></Panel>
}
function DraftReader({detail}:{detail:DraftDetail}){const d=detail.draft;return <article className="draft-reader"><div className="badges"><Badge tone={d.source_type==='ai'?'info':'ok'}>{d.source_type.toUpperCase()}</Badge><Badge>v{d.draft_version}</Badge><Badge>{d.status}</Badge></div><h2>{d.title||'Untitled draft'}</h2>{d.hook&&<blockquote>{d.hook}</blockquote>}<pre>{d.body}</pre><small>Parent {d.parent_draft_id||'root'} · Actor {d.created_by_actor||'AI'} · Invocation {d.ai_invocation_id||'N/A'}</small><h4>Claim references</h4>{detail.claim_references.map(r=><div key={r.id}>{r.section_key} · {r.claim_id} · {r.usage}</div>)}</article>}
