import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,RiskBadge,SectionState,Unavailable,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EditorialFormat,EditorialRisk,EditorialScore,EffectiveEditorialResponse,ScoreRunResponse,TrendSnapshot } from '../../workbenchTypes'
import { booleanLabel,editorialFormatLabel,sourceTypeLabel } from '../../uiLabels'

const dims=['emotion','information_gap','visual_value','user_relevance','discussion','novelty','extendability'] as const
type Dim=typeof dims[number]
const formats:EditorialFormat[]=['daily_compilation','quick_explainer','fact_check','deep_dive','entertainment','consumer_safety']
const risks:EditorialRisk[]=['R0','R1','R2','R3','R4']
const dimLabels:Record<Dim,string>={emotion:'情绪张力',information_gap:'信息缺口',visual_value:'视觉价值',user_relevance:'用户相关性',discussion:'讨论价值',novelty:'新鲜度',extendability:'延展性'}
const trendLabels:Record<string,string>={window:'统计窗口',signal_count:'信号数',new_signal_count:'新增信号',source_count:'信源数',platform_count:'平台数',signal_velocity:'信号速度',interaction_velocity:'互动速度',semantic_novelty:'语义新鲜度',cn_gap:'中文信息差',media_availability:'媒体素材可用性',cross_source:'跨信源',cross_platform:'跨平台',update_value:'更新价值',traffic_total:'综合流量分'}
const toLocal=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)}

export function EventTrendScoreSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[trend,setTrend]=useState<TrendSnapshot|null>(null);const[scores,setScores]=useState<EditorialScore[]>([]);const[effective,setEffective]=useState<EffectiveEditorialResponse|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[preview,setPreview]=useState<ScoreRunResponse|null>(null);const[mutating,setMutating]=useState(false)
 const[now]=useState(()=>new Date());const[start,setStart]=useState(()=>toLocal(new Date(now.getTime()-24*3600*1000)));const[end,setEnd]=useState(()=>toLocal(now));const[manual,setManual]=useState<Record<Dim,number>>(()=>Object.fromEntries(dims.map(d=>[d,50])) as Record<Dim,number>);const[manualRisk,setManualRisk]=useState<EditorialRisk>('R1');const[manualFormat,setManualFormat]=useState<EditorialFormat>('quick_explainer');const[manualReason,setManualReason]=useState('');const[overrideField,setOverrideField]=useState<Dim|'risk_level'|'recommended_format'>('emotion');const[overrideValue,setOverrideValue]=useState('50');const[overrideReason,setOverrideReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[t,s,e]=await Promise.all([api.event(eventId).then(v=>v.latest_trend),api.scores(eventId),api.effectiveScore(eventId)]);setTrend(t);setScores(s);setEffective(e)}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 const mutate=async(fn:()=>Promise<unknown>)=>{if(mutating)return;setMutating(true);try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}finally{setMutating(false)}}
 const runScore=async(apply:boolean)=>{if(!trend||mutating)return;setMutating(true);try{setError(null);const r=apply?await api.applyScore(eventId,trend.id):await api.previewScore(eventId,trend.id);setPreview(r);if(apply){await load();onChanged()}}catch(e){setError(FriendlyError(e))}finally{setMutating(false)}}
 const baseId=effective?.effective_base_score_id;const effectiveValues=effective?.effective_values
 const unavailable=useMemo(()=>{const raw=trend?.component_metrics.unavailable_reasons;return raw&&typeof raw==='object'?raw as Record<string,unknown>:{}},[trend])
 const overridePayload=()=>{let value:unknown=overrideValue;if(dims.includes(overrideField as Dim))value=Math.max(0,Math.min(100,Number(overrideValue)));return{[overrideField]:value,reason:overrideReason}}
 return <div className="wb-two-col align-start" aria-busy={mutating}>{mutating&&<p className="notice" role="status">正在提交并刷新趋势或评分…</p>}<Panel title="趋势"><SectionState loading={loading} error={error}>{trend?<><div className="trend-grid"><Value name="window" value={`${fmt(trend.window_start_at)} → ${fmt(trend.window_end_at)}`}/><Value name="signal_count" value={trend.signal_count}/><Value name="new_signal_count" value={trend.new_signal_count}/><Value name="source_count" value={trend.source_count}/><Value name="platform_count" value={trend.platform_count}/><Feature name="signal_velocity" value={trend.signal_velocity} available={trend.feature_availability.signal_velocity}/><Feature name="interaction_velocity" value={trend.interaction_velocity} available={trend.feature_availability.interaction_velocity} reason={str(unavailable.interaction_velocity)}/><Feature name="semantic_novelty" value={trend.semantic_novelty} available={trend.feature_availability.semantic_novelty} reason={str(unavailable.semantic_novelty)}/><Feature name="cn_gap" value={trend.cn_gap} available={trend.feature_availability.cn_gap} reason={str(unavailable.cn_gap)}/><Feature name="media_availability" value={null} available={trend.feature_availability.media_availability} reason={str(unavailable.media_availability)}/><Value name="cross_source" value={booleanLabel(trend.cross_source)}/><Value name="cross_platform" value={booleanLabel(trend.cross_platform)}/><Feature name="update_value" value={trend.update_value} available={trend.feature_availability.update_value}/></div></>:<Empty text="尚未计算趋势"/>}</SectionState>
  <div className="action-box"><h3>重新计算趋势</h3><p>页面加载时不会自动重算，请确认时间窗口后手动执行。</p><div className="inline-form"><label>窗口开始时间<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>窗口结束时间<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="primary" disabled={!canWrite||!start||!end} title={!canWrite?'配置执行者 ID 后才能操作；已合并事件只读':''} onClick={()=>void mutate(()=>api.calculateTrend(eventId,new Date(start).toISOString(),new Date(end).toISOString()))}>计算趋势</button></div></div>
 </Panel><Panel title="编辑评分"><SectionState loading={loading} error={null}><div className="score-comparison"><ScoreBlock title="原始 AI 评分" score={effective?.latest_ai_score}/><ScoreBlock title="最新人工评分" score={effective?.latest_human_score}/><EffectiveBlock values={effectiveValues} overridden={Boolean(effective?.applied_overrides.length)}/></div>{effective?.applied_overrides.length?<div className="override-history"><h4>人工覆盖记录</h4>{effective.applied_overrides.map(o=><div key={o.id}><Badge tone="warn">已应用人工覆盖</Badge> {Object.keys(o.overridden_fields).map(fieldLabel).join('、')} · {o.actor} · {o.reason} · {fmt(o.created_at)}</div>)}</div>:null}</SectionState>
  <div className="action-box"><h3>AI 评分</h3><p className="warning-text">预览与应用都是显式 AI 调用；在真实 Provider 环境中可能消耗 Token、成本与预算。</p><div className="actions"><button disabled={!canWrite||!trend} onClick={()=>void runScore(false)}>预览 AI 评分</button><button className="primary" disabled={!canWrite||!trend} onClick={()=>void runScore(true)}>应用 AI 评分</button></div>{preview&&<ScorePreview value={preview}/>}</div>
  <div className="action-box"><h3>人工评分</h3><div className="dimension-inputs">{dims.map(d=><label key={d}>{dimLabels[d]}<input type="number" min="0" max="100" value={manual[d]} onChange={e=>setManual({...manual,[d]:Number(e.target.value)})}/></label>)}</div><div className="inline-form"><label>风险等级<select value={manualRisk} onChange={e=>setManualRisk(e.target.value as EditorialRisk)}>{risks.map(r=><option key={r}>{r}</option>)}</select></label><label>推荐形式<select value={manualFormat} onChange={e=>setManualFormat(e.target.value as EditorialFormat)}>{formats.map(f=><option key={f} value={f}>{editorialFormatLabel[f]||f}</option>)}</select></label><label>评分理由<input value={manualReason} onChange={e=>setManualReason(e.target.value)}/></label><button className="primary" disabled={!canWrite||!manualReason.trim()} onClick={()=>void mutate(()=>api.manualScore(eventId,{trend_snapshot_id:trend?.id||null,...manual,risk_level:manualRisk,recommended_format:manualFormat,reason:manualReason}))}>创建人工评分</button></div></div>
  <div className="action-box"><h3>人工覆盖</h3><p>应用覆盖后，原始 AI 评分仍会保留并可查看。</p><div className="inline-form"><label>覆盖字段<select value={overrideField} onChange={e=>{const v=e.target.value as typeof overrideField;setOverrideField(v);setOverrideValue(v==='risk_level'?'R2':v==='recommended_format'?'quick_explainer':'50')}}>{[...dims,'risk_level','recommended_format'].map(f=><option key={f} value={f}>{fieldLabel(f)}</option>)}</select></label>{overrideField==='risk_level'?<label>覆盖值<select value={overrideValue} onChange={e=>setOverrideValue(e.target.value)}>{risks.map(r=><option key={r}>{r}</option>)}</select></label>:overrideField==='recommended_format'?<label>覆盖值<select value={overrideValue} onChange={e=>setOverrideValue(e.target.value)}>{formats.map(f=><option key={f} value={f}>{editorialFormatLabel[f]||f}</option>)}</select></label>:<label>覆盖值<input type="number" min="0" max="100" value={overrideValue} onChange={e=>setOverrideValue(e.target.value)}/></label>}<label>覆盖理由<input value={overrideReason} onChange={e=>setOverrideReason(e.target.value)}/></label><button className="primary" disabled={!canWrite||!baseId||!overrideReason.trim()} onClick={()=>void mutate(()=>api.overrideScore(eventId,baseId!,overridePayload()))}>应用人工覆盖</button></div></div>
  <details><summary>评分历史（{scores.length}）</summary>{scores.map(s=><ScoreBlock key={s.id} title={`${sourceTypeLabel[s.source_type]||s.source_type} · ${fmt(s.created_at)}`} score={s}/>)}</details>
 </Panel></div>
}
function str(v:unknown){return typeof v==='string'?v:undefined}
function Value({name,value}:{name:string;value:string|number}){return <div className="trend-value"><small>{trendLabels[name]||name}</small><strong>{value}</strong></div>}
function Feature({name,value,available,reason}:{name:string;value:number|null;available:boolean|undefined;reason?:string}){return <div className="trend-value"><small>{trendLabels[name]||name}</small><strong>{available===false||value===null?<Unavailable reason={reason}/>:value}</strong></div>}
function ScoreBlock({title,score}:{title:string;score:EditorialScore|null|undefined}){return <section className="score-block"><h4>{title}</h4>{!score?<Empty text="暂无评分"/>:<><div className="badges"><Badge tone={score.source_type==='human'?'ok':'info'}>{sourceTypeLabel[score.source_type]||score.source_type}</Badge><RiskBadge value={score.risk_level}/><Badge>{editorialFormatLabel[score.recommended_format]||score.recommended_format}</Badge></div><div className="score-dims">{dims.map(d=><span key={d}><small>{dimLabels[d]}</small><strong>{score[d]}</strong></span>)}<span><small>{trendLabels.traffic_total}</small><strong>{score.traffic_total.toFixed(1)}</strong></span></div><p>{score.model_reason||'暂无模型理由'}</p>{score.ai_invocation_id&&<small>AI 调用 ID：{score.ai_invocation_id}</small>}{score.source_reason&&<small>人工理由：{score.source_reason}</small>}</>}</section>}
function EffectiveBlock({values,overridden}:{values:Record<string,unknown>|null|undefined;overridden:boolean}){return <section className="score-block effective"><h4>当前生效评分 {overridden&&<Badge tone="warn">已应用人工覆盖</Badge>}</h4>{!values?<Empty text="暂无评分"/>:<><div className="badges"><RiskBadge value={(values.risk_level as EditorialRisk)||'R0'}/><Badge>{editorialFormatLabel[String(values.recommended_format)]||String(values.recommended_format||'暂无')}</Badge></div><div className="score-dims">{dims.map(d=><span key={d}><small>{dimLabels[d]}</small><strong>{String(values[d]??'暂无')}</strong></span>)}<span><small>{trendLabels.traffic_total}</small><strong>{String(values.traffic_total??'暂无')}</strong></span></div></>}</section>}
function ScorePreview({value}:{value:ScoreRunResponse}){return <div className="preview-box"><Badge tone="info">预览 · 未保存</Badge><RiskBadge value={value.risk_level}/><strong> 综合流量分 {value.traffic_total.toFixed(1)}</strong><div className="score-dims">{dims.map(d=><span key={d}><small>{dimLabels[d]}</small><strong>{value[d]}</strong></span>)}</div><p>{value.model_reason}</p>{value.ai_invocation_id&&<small>AI 调用 ID：{value.ai_invocation_id}</small>}</div>}
function fieldLabel(value:string){return value==='risk_level'?'风险等级':value==='recommended_format'?'推荐形式':dimLabels[value as Dim]||value}
