import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,SafeLink,SectionState,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EventCard,WorkbenchSignalPage } from '../../workbenchTypes'

export function EventSourcesSection({api,eventId,latestCard,canWrite,onSplit}:{api:WorkbenchApi;eventId:string;latestCard:EventCard|null;canWrite:boolean;onSplit:(newId:string|null)=>void}){
 const[page,setPage]=useState(1);const[data,setData]=useState<WorkbenchSignalPage|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[selected,setSelected]=useState<Set<string>>(new Set());const[reason,setReason]=useState('');const[title,setTitle]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api.signals(eventId,page,50))}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId,page]);useEffect(()=>{void load()},[load])
 const deterministic=useMemo(()=>data?.items.map(s=>({time:s.effective_at,text:s.title||`${s.platform} signal`,relation:s.relation}))||[],[data]);const timeline=latestCard?.timeline.length?latestCard.timeline:deterministic
 const split=async()=>{if(!reason.trim()||selected.size===0)return;if(!window.confirm(`Split ${selected.size} selected signals into a new Event?`))return;try{const result=await api.split(eventId,[...selected],reason.trim(),title.trim()||undefined) as {new_event_id?:string};setSelected(new Set());setReason('');setTitle('');await load();onSplit(result.new_event_id||null)}catch(e){setError(FriendlyError(e))}}
 const toggleSignal=(signalId:string,checked:boolean)=>{setSelected(prev=>{const next=new Set(prev);if(checked)next.add(signalId);else next.delete(signalId);return next})}
 return <div className="wb-two-col align-start"><Panel title="Sources"><SectionState loading={loading} error={error} empty={!data||data.items.length===0}>{data&&<><div className="source-list">{data.items.map(s=><article key={s.event_signal_id} className="timeline-source"><label className="signal-select"><input type="checkbox" disabled={!canWrite} checked={selected.has(s.signal_id)} onChange={e=>toggleSignal(s.signal_id,e.target.checked)}/><span className="sr-only">Select signal</span></label><div><div className="badges"><Badge tone="info">{s.relation}</Badge><Badge>{s.platform}</Badge><Badge>{s.source_name||'Unknown source'}</Badge></div><SafeLink url={s.original_url}>{s.title||s.original_url}</SafeLink><small>{s.author_name||'Unknown author'} · published {fmt(s.published_at)} · collected {fmt(s.collected_at)} · effective {fmt(s.effective_at)}</small></div></article>)}</div><div className="pager"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{data.total} signals</span><button disabled={!data.has_next} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}</SectionState>
   <div className="split-box"><h3>Human Split</h3><p className="muted-text">M3 clustering logic remains server-side. Select existing EventSignals only.</p><label>New Event title (optional)<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} required/></label><button className="danger" disabled={!canWrite||selected.size===0||!reason.trim()} title={!canWrite?'Configure Actor ID or use an active Event':''} onClick={()=>void split()}>Split selected signals</button></div>
  </Panel><Panel title="Timeline"><div className="timeline-note">{latestCard?.timeline.length?'Deterministic Event Card timeline':'Fallback timeline from Signal effective time; no LLM call'}</div>{timeline.length===0?<Empty text="No timeline items"/>:<ol className="timeline">{timeline.map((item,index)=><li key={index}><time>{fmt(asString(item.time)||asString(item.effective_at)||null)}</time><div>{asString(item.text)||asString(item.title)||asString(item.relation)||'Timeline item'}</div></li>)}</ol>}</Panel></div>
}
function asString(value:unknown):string|null{return typeof value==='string'?value:null}
