import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,JsonSummary,RiskBadge,SectionState } from '../workbench'
import { ClaimReferencePicker } from './ClaimReferencePicker'
import { DraftChainView } from './DraftChainView'
import type { DraftRefInput,WorkbenchApi } from '../../workbenchApi'
import type { CitationUsage,DraftDetail,DraftGenerationResponse,DraftType,EditorialDraft,EditorialPack,EventCard,EventEvidence } from '../../workbenchTypes'
import { citationUsageLabel,draftStatusLabel,draftTypeLabel,editorialFormatLabel,sourceTypeLabel } from '../../uiLabels'

export function EventDraftsSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[drafts,setDrafts]=useState<EditorialDraft[]>([]),[cards,setCards]=useState<EventCard[]>([]),[packs,setPacks]=useState<EditorialPack[]>([]);const[evidence,setEvidence]=useState<EventEvidence|null>(null);const[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const[cardId,setCardId]=useState(''),[packId,setPackId]=useState(''),[draftType,setDraftType]=useState<DraftType>('standard_90s'),[approval,setApproval]=useState(''),[preview,setPreview]=useState<DraftGenerationResponse|null>(null),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<DraftDetail|null>(null);const[body,setBody]=useState(''),[reason,setReason]=useState(''),[refs,setRefs]=useState<Record<string,CitationUsage>>({}),[changeNote,setChangeNote]=useState(''),[markdown,setMarkdown]=useState(''),[mutating,setMutating]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[d,c,p,e]=await Promise.all([api.drafts(eventId),api.cards(eventId),api.packs(eventId),api.evidence(eventId)]);setDrafts(d);setCards(c);setPacks(p);setEvidence(e);setCardId(v=>v||c[0]?.id||'');setPackId(v=>v||p[0]?.id||'')}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 const card=cards.find(c=>c.id===cardId)||null,pack=packs.find(p=>p.id===packId)||null,risk=card?.risk_level;const blocked=risk==='R4'&&pack?.recommended_format!=='fact_check',needsApproval=risk==='R3'&&!approval.trim();const selectedRefs=useMemo<DraftRefInput[]>(()=>Object.entries(refs).map(([claim_id,usage])=>({claim_id,usage,section_key:'main'})),[refs]);const latest=detail?Math.max(...detail.version_chain.map(v=>v.draft_version)):0,isLatest=detail?.draft.draft_version===latest
 const mutate=async(fn:()=>Promise<unknown>)=>{if(mutating)return;setMutating(true);try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}finally{setMutating(false)}}
 const generate=async(apply:boolean)=>{if(!cardId||!packId||mutating)return;setMutating(true);try{const payload={event_card_id:cardId,editorial_pack_id:packId,draft_type:draftType,...(approval.trim()?{risk_approval_reason:approval.trim()}: {})};const r=apply?await api.applyDraft(eventId,payload):await api.previewDraft(eventId,payload);setPreview(r);if(apply){await load();onChanged()}}catch(e){setError(FriendlyError(e))}finally{setMutating(false)}}
 const open=async(id:string)=>{setSelected(id);try{const d=await api.draft(eventId,id);setDetail(d);setBody(d.draft.body);setRefs(Object.fromEntries(d.claim_references.map(r=>[r.claim_id,r.usage])))}catch(e){setError(FriendlyError(e))}}
 return <Panel title="Draft、修订与 Markdown 导出"><SectionState loading={loading} error={error}>{!loading&&<>{mutating&&<p className="notice" role="status">正在提交并刷新 Draft 版本…</p>}
  <div className="draft-context"><label>Event Card<select value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">选择 Card</option>{cards.map(c=><option key={c.id} value={c.id}>{c.card_version}</option>)}</select></label><label>Editorial Pack<select value={packId} onChange={e=>setPackId(e.target.value)}><option value="">选择 Pack</option>{packs.map(p=><option key={p.id} value={p.id}>{p.pack_version} · {editorialFormatLabel[p.recommended_format]||p.recommended_format}</option>)}</select></label><label>Draft 类型<select value={draftType} onChange={e=>setDraftType(e.target.value as DraftType)}>{(['short_30s','standard_90s','deep_180s'] as DraftType[]).map(type=><option key={type} value={type}>{draftTypeLabel[type]||type}</option>)}</select></label><strong>内容形式：{pack?editorialFormatLabel[pack.recommended_format]||pack.recommended_format:'暂无'}</strong>{risk&&<RiskBadge value={risk}/>}</div>
  <div className="action-box"><h3>AI Draft 预览与应用</h3><p className="warning-text">预览与应用都是显式 AI 调用，可能消耗 Token、成本与预算；预览不会保存为正式 Draft。</p>{risk==='R3'&&<label>R3 人工批准理由<input aria-label="R3 人工批准理由" value={approval} onChange={e=>setApproval(e.target.value)}/></label>}{blocked&&<div className="error-banner">R4 风险事件只能生成事实核查类 Draft。</div>}<div className="actions"><button disabled={!canWrite||!cardId||!packId||blocked||needsApproval} title={!canWrite?'配置执行者 ID 后才能操作；已合并事件只读':needsApproval?'R3 需要填写人工批准理由':''} onClick={()=>void generate(false)}>预览 Draft</button><button className="primary" disabled={!canWrite||!cardId||!packId||blocked||needsApproval} onClick={()=>void generate(true)}>生成并应用</button></div>{preview&&<div className="preview-box"><Badge tone="info">{preview.mode==='preview'?'预览 · 未保存':preview.draft?'已应用 · 已保存':'已应用'}</Badge>{preview.ai_invocation_id&&<p>AI 调用 ID：{preview.ai_invocation_id}</p>}{preview.candidate&&<JsonSummary value={preview.candidate}/>}</div>}</div>
  <div className="wb-two-col align-start"><div><h3>Draft 版本链</h3><DraftChainView drafts={drafts} selectedId={selected} onSelect={id=>void open(id)}/></div><div>{detail?<DraftReader detail={detail}/>:<Empty text="选择一个 Draft 版本后在此阅读"/>}</div></div>
  <div className="action-box"><h3>人工 Draft 与修订</h3><p>编辑前会显示事实主张状态及允许的引用方式，最终规则仍以后端校验为准。</p><ClaimReferencePicker claims={evidence?.claims||[]} refs={refs} onChange={setRefs}/><label>创建理由 / 修订说明<input value={reason||changeNote} onChange={e=>detail?setChangeNote(e.target.value):setReason(e.target.value)}/></label><label>正文<textarea value={body} onChange={e=>setBody(e.target.value)} rows={9}/></label>{detail?<><p>基于父版本 v{detail.draft.draft_version} 创建修订，旧版本仍会保留。</p>{!isLatest&&<div className="error-banner">所选版本已不是最新版本，请刷新并选择最新版本后再修订。</div>}<button className="primary" disabled={!canWrite||!isLatest||!changeNote.trim()||!body.trim()||!selectedRefs.length} onClick={()=>void mutate(async()=>{try{await api.revise(eventId,detail.draft.id,{change_note:changeNote,body,references:selectedRefs,title:detail.draft.title||undefined})}catch(e){await load();throw e}})}>创建修订版本</button></>:<button className="primary" disabled={!canWrite||!cardId||!packId||!reason.trim()||!body.trim()||!selectedRefs.length} onClick={()=>void mutate(()=>api.humanDraft(eventId,{event_card_id:cardId,editorial_pack_id:packId,draft_type:draftType,reason,body,references:selectedRefs}))}>创建人工 Draft</button>}</div>
  <div className="action-box"><h3>导出 Markdown</h3><p>调用确定性导出器，不使用 AI，浏览器也不会重新拼装 Markdown。</p><button disabled={!packId} onClick={()=>void api.exportMarkdown(eventId,packId,selected||undefined).then(setMarkdown).catch(e=>setError(FriendlyError(e)))}>导出 Markdown</button>{markdown&&<pre className="markdown-view">{markdown}</pre>}</div>
 </>}</SectionState></Panel>
}
function DraftReader({detail}:{detail:DraftDetail}){const d=detail.draft;return <article className="draft-reader"><div className="badges"><Badge tone={d.source_type==='ai'?'info':'ok'}>{sourceTypeLabel[d.source_type]||d.source_type}</Badge><Badge>v{d.draft_version}</Badge><Badge>{draftStatusLabel[d.status]||d.status}</Badge></div><h2>{d.title||'未命名 Draft'}</h2>{d.hook&&<blockquote>{d.hook}</blockquote>}<pre>{d.body}</pre><small>父版本 {d.parent_draft_id||'根版本'} · 执行者 {d.created_by_actor||'AI'} · AI 调用 {d.ai_invocation_id||'无'}</small><h4>事实主张引用</h4>{detail.claim_references.map(r=><div key={r.id}>{r.section_key} · {r.claim_id} · {citationUsageLabel[r.usage]||r.usage}</div>)}</article>}
