import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,SafeLink,SectionState,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EventCard,WorkbenchSignalPage } from '../../workbenchTypes'

export function EventSourcesSection({api,eventId,latestCard,canWrite,onSplit}:{api:WorkbenchApi;eventId:string;latestCard:EventCard|null;canWrite:boolean;onSplit:(newId:string|null)=>void}){
 const[page,setPage]=useState(1);const[data,setData]=useState<WorkbenchSignalPage|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[selected,setSelected]=useState<Set<string>>(new Set());const[reason,setReason]=useState('');const[title,setTitle]=useState('');const[mutating,setMutating]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api.signals(eventId,page,50))}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId,page]);useEffect(()=>{void load()},[load])
 const deterministic=useMemo<Array<Record<string,unknown>>>(()=>data?.items.map(s=>({time:s.effective_at,text:s.title||`${s.platform} 信号`,relation:s.relation}))||[],[data]);const timeline:Array<Record<string,unknown>>=latestCard?.timeline.length?latestCard.timeline:deterministic
 const split=async()=>{if(!reason.trim()||selected.size===0||mutating)return;if(!window.confirm(`确认将选中的 ${selected.size} 条信号拆分为一个新事件？`))return;setMutating(true);try{const result=await api.split(eventId,[...selected],reason.trim(),title.trim()||undefined) as {new_event_id?:string};setSelected(new Set());setReason('');setTitle('');await load();onSplit(result.new_event_id||null)}catch(e){setError(FriendlyError(e))}finally{setMutating(false)}}
 const toggleSignal=(signalId:string,checked:boolean)=>{setSelected(prev=>{const next=new Set(prev);if(checked)next.add(signalId);else next.delete(signalId);return next})}
 return <div className="wb-two-col align-start" aria-busy={mutating}>{mutating&&<p className="notice" role="status">正在拆分事件并刷新信源…</p>}<Panel title="信源"><SectionState loading={loading} error={error} empty={!data||data.items.length===0}>{data&&<><div className="source-list">{data.items.map(s=><article key={s.event_signal_id} className="timeline-source"><label className="signal-select"><input type="checkbox" disabled={mutating||!canWrite} checked={selected.has(s.signal_id)} onChange={e=>toggleSignal(s.signal_id,e.target.checked)}/><span className="sr-only">选择信号</span></label><div><div className="badges"><Badge tone="info">{relationLabel(s.relation)}</Badge><Badge>{s.platform}</Badge><Badge>{s.source_name||'未知信源'}</Badge></div><SafeLink url={s.original_url}>{s.title||s.original_url}</SafeLink><small>{s.author_name||'未知作者'} · 发布于 {fmt(s.published_at)} · 采集于 {fmt(s.collected_at)} · 生效于 {fmt(s.effective_at)}</small></div></article>)}</div><div className="pager"><button disabled={mutating||page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>共 {data.total} 条信号</span><button disabled={mutating||!data.has_next} onClick={()=>setPage(p=>p+1)}>下一页</button></div></>}</SectionState>
   <div className="split-box"><h3>人工拆分事件</h3><p className="muted-text">聚类逻辑仍由服务端处理。这里只能从当前事件已有的信号中选择并拆分。</p><label>新事件标题（可选）<input disabled={mutating} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>拆分理由<input disabled={mutating} value={reason} onChange={e=>setReason(e.target.value)} required/></label><button className="danger" disabled={mutating||!canWrite||selected.size===0||!reason.trim()} title={!canWrite?'配置执行者 ID 后才能操作；已合并事件只读':''} onClick={()=>void split()}>{mutating?'正在拆分…':'拆分所选信号'}</button></div>
  </Panel><Panel title="时间线"><div className="timeline-note">{latestCard?.timeline.length?'使用最新 Event Card 中的确定性时间线':'根据原始信号生效时间生成后备时间线，不调用 AI'}</div>{timeline.length===0?<Empty text="暂无时间线记录"/>:<ol className="timeline">{timeline.map((item,index)=><li key={index}><time>{fmt(read(item,'time')||read(item,'effective_at')||null)}</time><div>{read(item,'text')||read(item,'title')||relationLabel(read(item,'relation'))||'时间线记录'}</div></li>)}</ol>}</Panel></div>
}
function read(item:Record<string,unknown>,key:string):string|null{const value=item[key];return typeof value==='string'?value:null}
function relationLabel(value:string|null){return value==='primary'?'主信号':value==='supporting'?'补充信号':value==='contradicting'?'反驳信号':value||'未标注关系'}
