import { useCallback,useEffect,useState } from 'react'
import { Empty,Panel } from '../common'
import { Badge,FriendlyError,JsonSummary,RiskBadge,SectionState,fmt } from '../workbench'
import type { WorkbenchApi } from '../../workbenchApi'
import type { EditorialPack,EventCard } from '../../workbenchTypes'

export function EventCardPackSection({api,eventId,canWrite,onChanged}:{api:WorkbenchApi;eventId:string;canWrite:boolean;onChanged:()=>void}){
 const[cards,setCards]=useState<EventCard[]>([]);const[packs,setPacks]=useState<EditorialPack[]>([]);const[cardId,setCardId]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[c,p]=await Promise.all([api.cards(eventId),api.packs(eventId)]);setCards(c);setPacks(p);setCardId(x=>x||c[0]?.id||'')}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 const mutate=async(fn:()=>Promise<unknown>)=>{try{setError(null);await fn();await load();onChanged()}catch(e){setError(FriendlyError(e))}}
 const latest=cards[0]||null,latestPack=packs[0]||null
 return <div className="wb-two-col align-start"><Panel title="Event Card"><SectionState loading={loading} error={error}>{latest?<CardView card={latest}/>:<Empty text="No Event Card"/>}</SectionState><div className="actions"><button disabled={!canWrite} title={!canWrite?'Configure Actor ID or use an active Event':''} onClick={()=>void mutate(()=>api.createCard(eventId,null))}>Create New Card</button></div><details><summary>Card history ({cards.length})</summary>{cards.map(c=><CardView key={c.id} card={c}/>)}</details></Panel>
  <Panel title="Editorial Pack"><SectionState loading={loading} error={error}>{latestPack?<PackView pack={latestPack}/>:<Empty text="No Editorial Pack"/>}</SectionState><div className="inline-form"><label>Event Card<select value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">Select Card</option>{cards.map(c=><option value={c.id} key={c.id}>{c.card_version} · {fmt(c.created_at)}</option>)}</select></label><button disabled={!canWrite||!cardId} onClick={()=>void mutate(()=>api.createPack(eventId,cardId))}>Create Editorial Pack</button></div><details><summary>Pack history ({packs.length})</summary>{packs.map(p=><PackView key={p.id} pack={p}/>)}</details></Panel></div>
}
function CardView({card}:{card:EventCard}){return <article className="artifact-card"><div className="badges"><Badge tone="info">{card.card_version}</Badge><RiskBadge value={card.risk_level}/><Badge>{card.recommended_format}</Badge><Badge>{card.generated_by}</Badge></div><h3>{card.title}</h3><p>{card.concise_summary}</p><div className="provenance"><span>created {fmt(card.created_at)}</span><span>input {card.input_hash.slice(0,12)}…</span><span>evidence {card.evidence_snapshot_hash.slice(0,12)}…</span><span>trend {card.trend_snapshot_id||'Unavailable'}</span><span>score {card.editorial_score_id}</span></div><details><summary>Claim groups / timeline / source summary</summary><div className="claim-id-grid"><span>confirmed {card.confirmed_claim_ids.length}</span><span>investigating {card.investigating_claim_ids.length}</span><span>single_source {card.single_source_claim_ids.length}</span><span>disputed {card.disputed_claim_ids.length}</span><span>false {card.false_claim_ids.length}</span><span>unknown {card.unknown_ids.length}</span></div><JsonSummary value={{timeline:card.timeline,source_summary:card.source_summary,effective_assessment:card.effective_assessment}}/></details></article>}
function PackView({pack}:{pack:EditorialPack}){return <article className="artifact-card"><div className="badges"><Badge tone="info">{pack.pack_version}</Badge><Badge>{pack.recommended_format}</Badge></div><div className="provenance"><span>created {fmt(pack.created_at)}</span><span>Card {pack.event_card_id}</span><span>input {pack.input_hash.slice(0,12)}…</span></div><Section name="Suggested angles" value={pack.suggested_angles}/><Section name="Source items" value={pack.source_items}/><Section name="Timeline" value={pack.timeline_items}/>{pack.material_items.length?<Section name="Material items" value={pack.material_items}/>:<div className="unavailable">MEDIA_METADATA_UNAVAILABLE</div>}<Section name="Warnings" value={pack.warnings}/><Section name="Unknowns" value={pack.unknown_items}/><Section name="Claim references" value={pack.claim_references}/></article>}
function Section({name,value}:{name:string;value:Array<Record<string,unknown>>}){return <details><summary>{name} ({value.length})</summary>{value.length?<JsonSummary value={value}/>:<Empty text={`No ${name.toLowerCase()}`}/>}</details>}
