import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,ErrorBanner } from '../components/common'
import { Badge,EventBadge,Metric,RiskBadge,fmt } from '../components/workbench'
import { editorialWorkflowError,type EditorialWorkflowApi } from '../editorialWorkflowApi'
import type { CandidateGenerationInput,CandidateGroup,CandidateListItem,CandidateListResponse,CandidatePreview,CandidateRun,DecisionHistoryItem,EditorialDecisionType } from '../editorialWorkflowTypes'
import type { PublicationApi } from '../publicationApi'
import type { EditorialRisk } from '../workbenchTypes'

const topViews=[20,10,5,3] as const
const decisions:EditorialDecisionType[]=['adopt','watch','drop','archive']
export function EditorialCandidatesPage({api,publicationApi,actorConfigured,onOpenEvent}:{api:EditorialWorkflowApi;publicationApi:PublicationApi;actorConfigured:boolean;onOpenEvent:(id:string)=>void}){
 const[runs,setRuns]=useState<CandidateRun[]>([]),[runId,setRunId]=useState(''),[topN,setTopN]=useState<number>(20),[group,setGroup]=useState<CandidateGroup|''>(''),[risk,setRisk]=useState<EditorialRisk|''>(''),[category,setCategory]=useState(''),[decisionFilter,setDecisionFilter]=useState<EditorialDecisionType|''>(''),[data,setData]=useState<CandidateListResponse|null>(null),[publicationCounts,setPublicationCounts]=useState<Record<string,number>>({}),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null)
 const[selected,setSelected]=useState<CandidateListItem|null>(null),[history,setHistory]=useState<DecisionHistoryItem[]>([]),[decision,setDecision]=useState<EditorialDecisionType>('watch'),[reason,setReason]=useState(''),[riskAck,setRiskAck]=useState(false),[confirmation,setConfirmation]=useState(false)
 const[businessDate,setBusinessDate]=useState(''),[timezone,setTimezone]=useState('Asia/Shanghai'),[asOf,setAsOf]=useState(''),[lookback,setLookback]=useState(24),[limit,setLimit]=useState(20),[preview,setPreview]=useState<CandidatePreview|null>(null)
 const loadRuns=useCallback(async(preferred?:string)=>{try{const rows=await api.runs();setRuns(rows);setRunId(current=>preferred&&rows.some(r=>r.id===preferred)?preferred:current&&rows.some(r=>r.id===current)?current:rows[0]?.id||'')}catch(e){setError(editorialWorkflowError(e))}},[api])
 useEffect(()=>{void loadRuns()},[loadRuns])
 const loadCandidates=useCallback(async()=>{if(!runId){setData(null);return}setLoading(true);setError(null);try{const[candidates,published]=await Promise.all([api.candidates({runId,topN,group:group||undefined,risk:risk||undefined,category:category||undefined}),publicationApi.publicationCounts()]);setData(candidates);setPublicationCounts(published)}catch(e){setError(editorialWorkflowError(e))}finally{setLoading(false)}},[api,publicationApi,runId,topN,group,risk,category])
 useEffect(()=>{void loadCandidates()},[loadCandidates])
 const visible=useMemo(()=>data?.items.filter(item=>!decisionFilter||item.current_editorial_decision?.decision===decisionFilter)||[],[data,decisionFilter])
 const counts=useMemo(()=>{const value={adopt:0,watch:0,drop:0,archive:0};for(const item of data?.items||[]){const current=item.current_editorial_decision?.decision;if(current)value[current]+=1}return value},[data])
 const generation=():CandidateGenerationInput=>({business_date:businessDate||undefined,timezone:timezone||undefined,as_of_at:asOf?new Date(asOf).toISOString():undefined,lookback_hours:lookback,requested_limit:limit})
 const doPreview=async()=>{setError(null);try{setPreview(await api.preview(generation()))}catch(e){setError(editorialWorkflowError(e))}}
 const doApply=async()=>{setError(null);try{const result=await api.apply(generation());setPreview(null);await loadRuns(result.run.id)}catch(e){setError(editorialWorkflowError(e))}}
 const choose=async(item:CandidateListItem)=>{setSelected(item);setDecision(item.current_editorial_decision?.decision||'watch');setReason('');setRiskAck(false);setConfirmation(false);try{setHistory(await api.history(item.candidate.event_id))}catch(e){setError(editorialWorkflowError(e))}}
 const submitDecision=async()=>{if(!selected)return;setError(null);try{await api.decide(selected.candidate.event_id,{candidate_id:selected.candidate.id,decision,expected_previous_decision_id:selected.current_editorial_decision?.id||null,risk_acknowledged:riskAck,reason,confirmation});setReason('');await loadCandidates();setHistory(await api.history(selected.candidate.event_id))}catch(e){setError(editorialWorkflowError(e))}}
 const selectedNeedsRisk=Boolean(selected&&(selected.candidate.effective_risk_level==='R3'||selected.candidate.effective_risk_level==='R4')&&decision==='adopt'),selectedNeedsConfirm=Boolean(selected&&(decision==='archive'||selected.current_editorial_decision?.decision==='archive'))
 return <div className="candidates-page"><section className="candidate-command"><div className="page-intro"><div><span className="eyebrow">今日候选池</span><h1>从候选快照完成编辑判断</h1><p>排名、编辑决定和真实发布记录彼此独立。</p></div><button onClick={()=>void loadRuns()}>刷新候选池</button></div><div className="filter-grid candidate-filters"><label>Run<select aria-label="Candidate Run" value={runId} onChange={e=>setRunId(e.target.value)}><option value="">No run</option>{runs.map(run=><option value={run.id} key={run.id}>{run.business_date} · {fmt(run.as_of_at)} · {run.candidate_count} candidates</option>)}</select></label><div className="segmented" aria-label="Candidate top view">{topViews.map(value=><button className={topN===value?'active':''} key={value} onClick={()=>setTopN(value)}>TOP{value}</button>)}</div><label>Group<select aria-label="Candidate group" value={group} onChange={e=>setGroup(e.target.value as CandidateGroup|'')}><option value="">All</option><option value="normal">normal</option><option value="review_required">review_required</option></select></label><label>Risk<select aria-label="Candidate risk" value={risk} onChange={e=>setRisk(e.target.value as EditorialRisk|'')}><option value="">All</option>{['R0','R1','R2','R3','R4'].map(value=><option key={value}>{value}</option>)}</select></label><label>Category<input aria-label="Candidate category" value={category} onChange={e=>setCategory(e.target.value)}/></label></div>{data&&<div className="run-summary"><span>{data.run.business_date} · {fmt(data.run.as_of_at)}</span><span>{data.run.candidate_count} / {data.run.eligible_event_count} eligible</span><span>{data.run.ranking_version}</span><span>Actor: {data.run.actor}</span></div>}<div className="decision-tabs" role="tablist" aria-label="Decision filter"><button className={!decisionFilter?'active':''} onClick={()=>setDecisionFilter('')}>All {data?.items.length??0}</button><button className={decisionFilter==='watch'?'active':''} onClick={()=>setDecisionFilter('watch')}>Watch {counts.watch}</button><button className={decisionFilter==='adopt'?'active':''} onClick={()=>setDecisionFilter('adopt')}>Adopt {counts.adopt}</button><button className={decisionFilter==='drop'?'active':''} onClick={()=>setDecisionFilter('drop')}>Drop {counts.drop}</button><button className={decisionFilter==='archive'?'active':''} onClick={()=>setDecisionFilter('archive')}>Archive {counts.archive}</button></div></section><ErrorBanner error={error}/>
  <div className="candidate-workspace"><section className="candidate-list" aria-label="候选排名列表">{loading&&<div className="section-state">Loading candidates…</div>}{!loading&&runId&&visible.length===0&&<Empty text="No Candidates match this view"/>}{!loading&&visible.map(item=>{const candidate=item.candidate,current=item.current_editorial_decision,published=publicationCounts[candidate.event_id]||0,active=selected?.candidate.id===candidate.id;return <article className={`candidate-row ${active?'selected':''}`} key={candidate.id||`${candidate.event_id}-${candidate.rank}`}><button className="candidate-select" onClick={()=>void choose(item)}><span className="rank-number">{String(candidate.rank).padStart(2,'0')}</span><span className="candidate-title"><strong>{candidate.event_title_snapshot}</strong><small>{candidate.category_snapshot||'Uncategorized'} · {candidate.source_count_snapshot} sources / {candidate.platform_count_snapshot} platforms</small></span><span className="candidate-score"><strong>{candidate.effective_traffic_total.toFixed(1)}</strong><small>Effective traffic</small></span><span className="candidate-evidence"><span>{candidate.evidence_summary.total??0} claims</span><small>{candidate.open_unknown_count} Unknowns</small></span><span className="badges"><RiskBadge value={candidate.effective_risk_level}/>{current&&<Badge tone={current.decision==='archive'?'danger':'info'}>{current.decision}</Badge>}{published>0&&<Badge tone="ok">Published · {published}</Badge>}{item.stale_indicator&&<Badge tone="warn">Possibly stale</Badge>}</span></button><div className="candidate-row-actions"><EventBadge value={candidate.event_status_snapshot}/><button onClick={()=>onOpenEvent(candidate.event_id)}>Open Workbench</button></div></article>})}</section>
   <aside className="decision-rail">{selected?<><div className="rail-heading"><span className="eyebrow">当前聚焦候选</span><button onClick={()=>setSelected(null)}>关闭</button></div><div className="rail-title"><span className="rank-number">{String(selected.candidate.rank).padStart(2,'0')}</span><h2>{selected.candidate.event_title_snapshot}</h2></div><div className="badges"><RiskBadge value={selected.candidate.effective_risk_level}/>{selected.candidate.category_snapshot&&<Badge>{selected.candidate.category_snapshot}</Badge>}{selected.current_editorial_decision&&<Badge tone="info">Current: {selected.current_editorial_decision.decision}</Badge>}</div><dl className="rail-facts"><div><dt>Evidence</dt><dd>{selected.candidate.evidence_summary.total??0} claims</dd></div><div><dt>Sources / Platforms</dt><dd>{selected.candidate.source_count_snapshot} / {selected.candidate.platform_count_snapshot}</dd></div><div><dt>Open Unknowns</dt><dd>{selected.candidate.open_unknown_count}</dd></div><div><dt>Recommended format</dt><dd>{selected.candidate.recommended_format}</dd></div></dl><div className="decision-form"><h3>编辑决定</h3><div className="decision-options">{decisions.map(value=><button className={decision===value?'active':''} key={value} onClick={()=>setDecision(value)}>{value}</button>)}</div><label>Reason<textarea aria-label="Decision reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for every decision"/></label>{selectedNeedsRisk&&<label className="check-field"><input aria-label="Risk acknowledgement" type="checkbox" checked={riskAck} onChange={e=>setRiskAck(e.target.checked)}/> Acknowledge {selected.candidate.effective_risk_level} risk</label>}{selectedNeedsConfirm&&<label className="check-field"><input aria-label="Decision confirmation" type="checkbox" checked={confirmation} onChange={e=>setConfirmation(e.target.checked)}/> Confirm Archive / Restore</label>}<button className="primary" disabled={!actorConfigured||!reason.trim()||(selectedNeedsRisk&&!riskAck)||(selectedNeedsConfirm&&!confirmation)} onClick={()=>void submitDecision()}>保存编辑决定</button>{!actorConfigured&&<small className="warning-text">Configure Actor ID before writing a decision.</small>}</div><details className="decision-history"><summary>Decision History ({history.length})</summary>{history.length===0?<Empty text="No decision history"/>:<ol>{history.map(item=><li key={item.decision.id}><strong>{item.decision.decision}</strong><span>{fmt(item.decision.created_at)} · {item.decision.actor}</span><small>{item.decision.reason}</small></li>)}</ol>}</details><button className="secondary-action" onClick={()=>onOpenEvent(selected.candidate.event_id)}>打开 Event Workbench</button></>:<div className="empty rail-empty"><strong>选择一条候选</strong><span>在左侧查看排名和快照，再在此处记录人工判断。</span></div>}</aside></div>
  <details className="candidate-generation"><summary>Generate Daily Candidate Pool</summary><div className="notice">Preview is side-effect free. Apply is deterministic DB processing and requires Actor + explicit confirmation. Candidate generation 不调用 AI，也不会因 Publication/Performance 修改 candidate-ranking-v1。</div><div className="filter-grid"><label>Business date<input aria-label="Business date" type="date" value={businessDate} onChange={e=>setBusinessDate(e.target.value)}/></label><label>Timezone<input aria-label="Business timezone" value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><label>As of<input aria-label="Candidate as of" type="datetime-local" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><label>Lookback hours<input aria-label="Lookback hours" type="number" min={1} max={168} value={lookback} onChange={e=>setLookback(Number(e.target.value))}/></label><label>Limit<input aria-label="Candidate limit" type="number" min={1} max={100} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label></div><div className="actions"><button onClick={()=>void doPreview()}>Preview Pool</button><button className="primary" disabled={!actorConfigured} onClick={()=>void doApply()}>Apply Pool</button>{!actorConfigured&&<small className="warning-text">Configure Actor ID before Apply.</small>}</div>{preview&&<div className="metric-grid compact"><Metric label="Preview candidates" value={preview.candidate_count}/><Metric label="Eligible" value={preview.eligible_event_count}/><Metric label="Skipped" value={preview.skipped_event_count}/><Metric label="Input hash" value={preview.input_hash.slice(0,12)}/><Metric label="Ranking" value={preview.ranking_version}/><Metric label="As of" value={fmt(preview.as_of_at)}/></div>}</details>
 </div>
}
