import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { AdminApi } from '../api'
import { WorkbenchApi } from '../workbenchApi'
import { EditorialEventsPage } from './EditorialEventsPage'

const baseEvent={summary:'summary',category:'technology',status:'growing',first_seen_at:'2026-08-09T08:00:00Z',last_updated_at:'2026-08-09T10:00:00Z',primary_language:'zh',entities:[],keywords:[],source_count:4,platform_count:2,created_at:'2026-08-09T08:00:00Z',updated_at:'2026-08-09T10:00:00Z'}
const trend={id:'10000000-0000-4000-8000-000000000001',event_id:'e1',calculation_version:'v1',window_start_at:'2026-08-09T08:00:00Z',window_end_at:'2026-08-09T10:00:00Z',signal_count:4,new_signal_count:2,source_count:3,platform_count:2,signal_velocity:1.5,interaction_velocity:null,cross_source:true,cross_platform:true,semantic_novelty:null,cn_gap:null,update_value:60,feature_availability:{signal_velocity:true,interaction_velocity:false},component_metrics:{},input_hash:'a'.repeat(64),created_at:'2026-08-09T10:00:00Z'}
const effective={emotion:70,information_gap:70,visual_value:60,user_relevance:70,discussion:65,novelty:55,extendability:70,traffic_total:66.5,risk_level:'R3',recommended_format:'quick_explainer',model_reason:'reason',base_score_id:'score',base_source_type:'human'}
function item(id:string,merged:string|null=null){return{event:{...baseEvent,id,title:`Event ${id}`,merged_into_event_id:merged},latest_trend:{...trend,event_id:id},latest_ai_score:null,latest_human_score:null,effective_editorial:effective,human_override_applied:true,applied_override_count:1,evidence_counts:{confirmed:2,investigating:1,single_source:1,disputed:1,false:1},evidence_total:6,open_unknown_count:2,card_count:1,latest_card:null,latest_card_id:'card',latest_pack:null,draft_count:2,latest_draft_id:'draft'}}
function api(calls:string[]){vi.stubGlobal('fetch',vi.fn(async(url:string|URL|Request)=>{const u=String(url);calls.push(u);const parsed=new URL(u);const page=Number(parsed.searchParams.get('page')||1);const items=page===1?[item('e1'),item('e2','target-event')]:[item('e3')];return Response.json({items,page,page_size:20,total:3,has_next:page===1})}));return new WorkbenchApi(new AdminApi({apiBaseUrl:'http://api',adminToken:'token',actorId:'editor'}))}

afterEach(()=>vi.unstubAllGlobals())

it('loads the event workspace, shows effective fields and localized merged/human override badges',async()=>{const calls:string[]=[];const open=vi.fn();render(<EditorialEventsPage api={api(calls)} onOpenEvent={open}/>);await screen.findByText('Event e1');expect(screen.getAllByText(/已合并/).length).toBeGreaterThan(1);expect(screen.getAllByText('已人工覆盖').length).toBeGreaterThan(0);expect(screen.getAllByText('风险 R3').length).toBeGreaterThan(0);expect(screen.getAllByText(/66.5/).length).toBeGreaterThan(0);expect(screen.queryByText(/raw_payload|credential|Authorization/i)).toBeNull();await userEvent.click(screen.getByRole('button',{name:'Event e1'}));expect(open).toHaveBeenCalledWith('e1')})

it('supports pagination and lifecycle/presence filters while distinguishing lifecycle from candidate rank and decisions',async()=>{const calls:string[]=[];render(<EditorialEventsPage api={api(calls)} onOpenEvent={()=>undefined}/>);await screen.findByText('Event e1');await userEvent.click(screen.getByRole('button',{name:'下一页'}));await screen.findByText('Event e3');expect(calls.some(x=>x.includes('page=2'))).toBe(true);await userEvent.selectOptions(screen.getByLabelText('生命周期'),'growing');await waitFor(()=>expect(calls.some(x=>x.includes('status=growing'))).toBe(true));await userEvent.selectOptions(screen.getByLabelText('是否有证据'),'true');await waitFor(()=>expect(calls.some(x=>x.includes('has_evidence=true'))).toBe(true));expect(screen.getByText(/事件生命周期、候选排名和人工编辑判断相互独立/)).toBeInTheDocument()})
