import { useCallback,useEffect,useState } from 'react'
import { Empty,ErrorBanner,Panel } from '../components/common'
import { Metric,RiskBadge } from '../components/workbench'
import type { WorkbenchApi } from '../workbenchApi'
import type { WorkbenchOverview } from '../workbenchTypes'

export function EditorialOverviewPage({api,onNavigate}:{api:WorkbenchApi;onNavigate:(key:string)=>void}){
 const[data,setData]=useState<WorkbenchOverview|null>(null);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api.overview())}catch(e){setError(e instanceof Error?e.message:'Overview load failed')}finally{setLoading(false)}},[api])
 useEffect(()=>{void load()},[load])
 if(loading)return <Panel title="Editorial Overview"><div className="section-state" role="status">Loading overview…</div></Panel>
 if(error)return <Panel title="Editorial Overview"><ErrorBanner error={error}/><button onClick={()=>void load()}>Retry</button></Panel>
 if(!data)return <Panel title="Editorial Overview"><Empty text="No overview data"/></Panel>
 const life=data.lifecycle_counts,h=data.collection_health,a=data.artifact_counts,w=data.candidate_workflow
 const decisions=(w?.current_decision_counts.adopt??0)+(w?.current_decision_counts.watch??0)+(w?.current_decision_counts.drop??0)+(w?.current_decision_counts.archive??0)
 return <>
  <section className="overview-hero"><div><span className="eyebrow">今日重点关注</span><h1>{w?.run_exists?'候选池已生成':'今日候选池尚未生成'}</h1><p>{w?.run_exists?`${w.latest_run?.candidate_count??0} 条候选 · ${decisions} 条已有编辑判断`:'先生成或查看候选快照，再开始人工判断。'}</p></div><div className="hero-actions"><RiskBadge value={data.high_risk_event_count>0?'R3':'R1'}/><small>{data.high_risk_event_count} 条高风险事件</small><button className="primary" onClick={()=>onNavigate('candidates')}>进入今日候选</button></div></section>
  <section className="stat-strip" aria-label="编辑概览统计"><Metric label="活跃事件" value={data.active_event_count} help={`${data.recent_updated_event_count_24h} 条在 24h 内更新`}/><Metric label="今日新增" value={data.recent_new_event_count_24h}/><Metric label="待确认 Unknown" value={data.open_unknown_count}/><Metric label="已采用" value={w?.current_decision_counts.adopt??0}/><Metric label="高风险" value={data.high_risk_event_count} help="Effective R3 / R4"/></section>
  <section className="overview-grid"><div className="overview-section"><div className="section-heading"><div><span className="eyebrow">编辑优先队列</span><h2>从候选快照开始今天的判断</h2></div><button onClick={()=>void load()}>刷新</button></div><div className="priority-list"><div><span>候选池</span><strong>{w?.run_exists?`${w.latest_run?.candidate_count??0} 条可查看`:'尚未生成'}</strong><button className="link-button" onClick={()=>onNavigate('candidates')}>打开候选池</button></div><div><span>风险与证据</span><strong>{data.high_risk_event_count} 条高风险 · {data.events_with_evidence_count} 条已有证据</strong><button className="link-button" onClick={()=>onNavigate('events')}>查看事件</button></div><div><span>生命周期</span><strong>{(['emerging','growing','stable','declining','resolved'] as const).map(k=>`${k} ${life[k]}`).join(' · ')}</strong><span className="muted-text">基于当前事件快照</span></div></div></div><div className="overview-section situation"><div className="section-heading"><div><span className="eyebrow">今日态势</span><h2>仅展示已有业务快照</h2></div></div><div className="decision-distribution"><div><small>Adopt</small><strong>{w?.current_decision_counts.adopt??0}</strong></div><div><small>Watch</small><strong>{w?.current_decision_counts.watch??0}</strong></div><div><small>Drop</small><strong>{w?.current_decision_counts.drop??0}</strong></div><div><small>Archive</small><strong>{w?.current_decision_counts.archive??0}</strong></div></div><p className="muted-text">不伪造趋势历史；候选、决定与风险均来自当前 API 返回的真实快照。</p></div></section>
  <section className="workflow-strip" aria-label="今日工作流">{[['候选池',w?.latest_run?.candidate_count??0],['人工判断',decisions],['内容产物',a.event_cards+a.editorial_packs+a.drafts],['发布记录',0],['效果回流',0]].map(([label,value],index)=><div key={String(label)}><span>{index+1}</span><small>{label}</small><strong>{String(value)}</strong></div>)}</section>
  <div className="notice compact-notice"><strong>编辑边界。</strong> Candidate ranking 是持久化 deterministic snapshot；Human Editorial Decision 不会修改 Event lifecycle 或 algorithmic rank。</div>
  <div className="wb-two-col">
   <Panel title="Collection / Risk Health"><div className="metric-grid compact"><Metric label="Failed Runs · 24h" value={h.failed_runs_24h}/><Metric label="Risk-paused Runs · 24h" value={h.paused_risk_runs_24h}/><Metric label="Open Risk Events" value={h.open_risk_events}/><Metric label="Paused Accounts" value={h.paused_accounts}/><Metric label="Checkpoints" value={h.checkpoint_count}/></div><div className="actions"><button onClick={()=>onNavigate('runs')}>Runs</button><button onClick={()=>onNavigate('risk')}>Accounts / Risk</button><button onClick={()=>onNavigate('checkpoints')}>Checkpoints</button><button onClick={()=>onNavigate('sources')}>Sources</button></div></Panel>
   <Panel title="Production AI Provider Validation"><div className="provider-status"><RiskBadge value="R2"/><strong>{data.production_ai_provider_validation}</strong></div><p className="muted-text">M5-B candidate generation never invokes AI. Production validation remains an explicit operational gate.</p><div className="actions"><button onClick={()=>onNavigate('ai-providers')}>AI Providers</button><button onClick={()=>onNavigate('ai-routes')}>AI Routes</button><button onClick={()=>onNavigate('ai-budgets')}>AI Budgets</button></div></Panel>
  </div>
 </>
}
