import { render,screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { AdminApi } from '../api'
import { EditorialWorkflowApi } from '../editorialWorkflowApi'
import { PublicationApi } from '../publicationApi'
import { EditorialCandidatesPage } from './EditorialCandidatesPage'

const run={id:'run-1',business_date:'2026-08-10',timezone:'Asia/Shanghai',as_of_at:'2026-08-10T10:00:00Z',window_start_at:'2026-08-09T10:00:00Z',window_end_at:'2026-08-10T10:00:00Z',ranking_version:'candidate-ranking-v1',requested_limit:20,status:'succeeded',input_hash:'a'.repeat(64),scanned_event_count:2,eligible_event_count:2,candidate_count:2,skipped_event_count:0,skip_summary:{},mode:'apply',actor:'editor',error_code:null,created_at:'2026-08-10T10:00:01Z',finished_at:'2026-08-10T10:00:01Z'}
const candidate=(rank:number,risk:'R2'|'R3',decision:'watch'|'adopt'|null)=>({candidate:{id:`candidate-${rank}`,run_id:run.id,event_id:`event-${rank}`,rank,candidate_group:risk==='R3'?'review_required':'normal',event_title_snapshot:`Candidate ${rank}`,category_snapshot:'social',event_status_snapshot:'growing',event_last_updated_at_snapshot:'2026-08-10T09:00:00Z',source_count_snapshot:3,platform_count_snapshot:2,trend_snapshot_id:null,base_editorial_score_id:'score',effective_assessment_hash:'b'.repeat(64),effective_traffic_total:90-rank,effective_risk_level:risk,recommended_format:'quick_explainer',open_unknown_count:1,evidence_summary:{total:2,confirmed:1,disputed:0},ranking_components:{update_value:50,signal_velocity:3},card_exists_snapshot:true,draft_exists_snapshot:false,candidate_context_hash:'c'.repeat(64),created_at:'2026-08-10T10:00:01Z'},current_event_status:'growing',merged_into_event_id:null,current_editorial_decision:decision?{id:`decision-${rank}`,event_id:`event-${rank}`,candidate_id:`candidate-${rank}`,decision,previous_decision_id:null,candidate_context_hash:'c'.repeat(64),risk_acknowledged:false,risk_level_snapshot:risk,effective_traffic_total_snapshot:90-rank,reason:'previous',actor:'editor',created_at:'2026-08-10T10:01:00Z'}:null,stale_indicator:null})
afterEach(()=>vi.unstubAllGlobals())

it('shows one snapshot with derived TOP views and Human Decision separately',async()=>{const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(raw:string|URL|Request,init:RequestInit={})=>{const url=String(raw);calls.push(`${init.method||'GET'} ${url}`);if(url.includes('/candidate-runs?'))return Response.json([run]);if(url.includes('/candidates'))return Response.json({run,items:[candidate(1,'R2','watch'),candidate(2,'R3',null)],total:2,top_n:20});if(url.includes('/publications?'))return Response.json({items:[],total:0,page:1,page_size:100});if(url.includes('/decisions'))return Response.json([]);return Response.json({decision:{...candidate(2,'R3','adopt').current_editorial_decision,id:'new-decision'},reused:false})}));const adminApi=new AdminApi({apiBaseUrl:'http://api',adminToken:'token',actorId:'editor'});const api=new EditorialWorkflowApi(adminApi);const publicationApi=new PublicationApi(adminApi);render(<EditorialCandidatesPage api={api} publicationApi={publicationApi} actorConfigured onOpenEvent={()=>undefined}/>);expect(await screen.findByText('Candidate 1')).toBeInTheDocument();expect(screen.getByText('观察')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'TOP3'}));expect(calls.some(call=>call.includes('top_n=3'))).toBe(true);await userEvent.click(screen.getByRole('button',{name:/Candidate 1/}));expect(await screen.findByText('当前聚焦候选')).toBeInTheDocument()})

it('requires risk acknowledgement for R3 adopt and keeps apply disabled without Actor',async()=>{vi.stubGlobal('fetch',vi.fn(async(raw:string|URL|Request)=>{const url=String(raw);if(url.includes('/candidate-runs?'))return Response.json([run]);if(url.includes('/candidates'))return Response.json({run,items:[candidate(2,'R3',null)],total:1,top_n:20});if(url.includes('/publications?'))return Response.json({items:[],total:0,page:1,page_size:100});if(url.includes('/decisions'))return Response.json([]);return Response.json({})}));const adminApi=new AdminApi({apiBaseUrl:'http://api',adminToken:'token',actorId:''});const api=new EditorialWorkflowApi(adminApi);const publicationApi=new PublicationApi(adminApi);render(<EditorialCandidatesPage api={api} publicationApi={publicationApi} actorConfigured={false} onOpenEvent={()=>undefined}/>);await screen.findByText('Candidate 2');expect(screen.getByRole('button',{name:'应用候选池'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:/Candidate 2/}));await userEvent.click(screen.getByRole('button',{name:'采用'}));expect(screen.getByLabelText('风险确认')).toBeInTheDocument();expect(screen.getByRole('button',{name:'保存编辑决定'})).toBeDisabled()})
