import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,ErrorBanner,Panel } from '../components/common'
import { Badge,EventBadge,Metric,RiskBadge,fmt } from '../components/workbench'
import { decisionLabel,eventStatusLabel } from '../uiLabels'
import type { WorkbenchApi } from '../workbenchApi'
import type { EditorialDecision,EditorialRisk,EventQuery,EventStatus,WorkbenchEventPage } from '../workbenchTypes'

const presence=[['','不限'],['true','有'],['false','无']] as const
export function EditorialEventsPage({api,onOpenEvent}:{api:WorkbenchApi;onOpenEvent:(id:string)=>void}){
 const[page,setPage]=useState(1);const[q,setQ]=useState('');const[status,setStatus]=useState<EventStatus|''>('');const[category,setCategory]=useState('');const[risk,setRisk]=useState<EditorialRisk|''>('');const[decision,setDecision]=useState<EditorialDecision|''>('');const[includeMerged,setIncludeMerged]=useState(false);const[hasEvidence,setHasEvidence]=useState('');const[hasScore,setHasScore]=useState('');const[hasDraft,setHasDraft]=useState('');const[updatedFrom,setUpdatedFrom]=useState('');const[updatedTo,setUpdatedTo]=useState('');const[sortBy,setSortBy]=useState<EventQuery['sortBy']>('last_updated_at');const[sortDirection,setSortDirection]=useState<'asc'|'desc'>('desc');const[data,setData]=useState<WorkbenchEventPage|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
 const query=useMemo<EventQuery>(()=>({page,pageSize:20,q:q||undefined,status:status||undefined,category:category||undefined,risk:risk||undefined,decision:decision||undefined,includeMerged,hasEvidence:hasEvidence?hasEvidence==='true':undefined,hasScore:hasScore?hasScore==='true':undefined,hasDraft:hasDraft?hasDraft==='true':undefined,updatedFrom:updatedFrom||undefined,updatedTo:updatedTo||undefined,sortBy,sortDirection}),[page,q,status,category,risk,decision,includeMerged,hasEvidence,hasScore,hasDraft,updatedFrom,updatedTo,sortBy,sortDirection])
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api.events(query))}catch(e){setError(e instanceof Error?e.message:'加载事件列表失败')}finally{setLoading(false)}},[api,query]);useEffect(()=>{void load()},[load]);const resetPage=()=>setPage(1)
 return <Panel title="事件" actions={<button onClick={()=>void load()}>刷新</button>}>
  <div className="page-intro"><p>浏览、筛选并进入事件工作台进行核验和编辑判断。</p><div className="notice"><strong>事件生命周期、候选排名和人工编辑判断相互独立。</strong></div></div>
  <div className="filter-grid">
   <label>搜索<input aria-label="搜索事件" value={q} onChange={e=>{setQ(e.target.value);resetPage()}} placeholder="搜索标题或摘要"/></label>
   <label>生命周期<select aria-label="生命周期" value={status} onChange={e=>{setStatus(e.target.value as EventStatus|'');resetPage()}}><option value="">全部</option>{['emerging','growing','stable','declining','resolved'].map(v=><option key={v} value={v}>{eventStatusLabel[v]}</option>)}</select></label>
   <label>编辑决定<select aria-label="编辑决定筛选" value={decision} onChange={e=>{setDecision(e.target.value as EditorialDecision|'');resetPage()}}><option value="">全部</option>{['adopt','watch','drop','archive'].map(v=><option key={v} value={v}>{decisionLabel[v]}</option>)}</select></label>
   <label>分类<input aria-label="事件分类" value={category} onChange={e=>{setCategory(e.target.value);resetPage()}}/></label><label>风险<select aria-label="风险等级" value={risk} onChange={e=>{setRisk(e.target.value as EditorialRisk|'');resetPage()}}><option value="">全部</option>{['R0','R1','R2','R3','R4'].map(v=><option key={v}>{v}</option>)}</select></label>
   <details className="more-filters"><summary>更多筛选</summary><div className="filter-grid"><label>是否有证据<select aria-label="是否有证据" value={hasEvidence} onChange={e=>{setHasEvidence(e.target.value);resetPage()}}>{presence.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>是否有评分<select aria-label="是否有评分" value={hasScore} onChange={e=>{setHasScore(e.target.value);resetPage()}}>{presence.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>是否有草稿<select aria-label="是否有草稿" value={hasDraft} onChange={e=>{setHasDraft(e.target.value);resetPage()}}>{presence.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>更新时间起<input aria-label="更新时间起" type="datetime-local" value={updatedFrom} onChange={e=>{setUpdatedFrom(e.target.value);resetPage()}}/></label><label>更新时间止<input aria-label="更新时间止" type="datetime-local" value={updatedTo} onChange={e=>{setUpdatedTo(e.target.value);resetPage()}}/></label><label>排序<select aria-label="排序字段" value={sortBy} onChange={e=>{setSortBy(e.target.value as EventQuery['sortBy']);resetPage()}}><option value="last_updated_at">最近更新</option><option value="first_seen_at">首次发现</option><option value="traffic_total">有效评分</option></select></label><label>排序方向<select aria-label="排序方向" value={sortDirection} onChange={e=>{setSortDirection(e.target.value as 'asc'|'desc');resetPage()}}><option value="desc">降序</option><option value="asc">升序</option></select></label><label className="check-field"><input type="checkbox" checked={includeMerged} onChange={e=>{setIncludeMerged(e.target.checked);resetPage()}}/> 包含已合并事件</label></div></details>
  </div><ErrorBanner error={error}/>{loading&&<div className="section-state" role="status">正在加载事件…</div>}
  {!loading&&data&&data.items.length===0&&<Empty text={q||status||category||risk||decision||hasEvidence||hasScore||hasDraft?'没有符合当前筛选条件的事件':'当前还没有事件'}/>} {!loading&&data&&data.items.length===0&&<p className="muted-text">可以调整筛选条件，或等待新的采集结果进入事件池。</p>}
  {!loading&&data&&data.items.length>0&&<div className="event-list">{data.items.map(item=>{const e=item.event,s=item.effective_editorial;return <article className="event-row" key={e.id}><div className="event-main"><button className="link-button event-title" onClick={()=>onOpenEvent(e.id)}>{e.title}</button><div className="badges"><EventBadge value={e.status}/>{e.category&&<Badge>{e.category}</Badge>}{e.merged_into_event_id&&<Badge tone="danger">已合并 → {e.merged_into_event_id.slice(0,8)}</Badge>}{item.human_override_applied&&<Badge tone="warn">已人工覆盖</Badge>}{item.current_editorial_decision&&<Badge tone={item.current_editorial_decision.decision==='archive'?'danger':'info'}>人工：{decisionLabel[item.current_editorial_decision.decision]}</Badge>}{item.latest_candidate&&<Badge>算法排名 #{item.latest_candidate.rank}</Badge>}</div><small>首次发现 {fmt(e.first_seen_at)} · 最近更新 {fmt(e.last_updated_at)}</small></div><div className="event-stats"><Metric label="信源 / 平台" value={`${e.source_count} / ${e.platform_count}`}/><Metric label="趋势" value={item.latest_trend?`${item.latest_trend.new_signal_count} 条新增 · ${item.latest_trend.signal_velocity??'暂无'}`:'尚未计算'}/><Metric label="有效评分" value={s?s.traffic_total.toFixed(1):'尚未评分'}/><Metric label="风险" value={s?<RiskBadge value={s.risk_level}/>:'尚未评分'}/><Metric label="建议形式" value={s?.recommended_format||'暂无'}/><Metric label="证据" value={`${item.evidence_total} 条`} help={`已确认 ${item.evidence_counts.confirmed} · 单一信源 ${item.evidence_counts.single_source} · 争议 ${item.evidence_counts.disputed}`}/><Metric label="待确认点" value={item.open_unknown_count}/><Metric label="内容产物" value={`Card ${item.card_count?'有':'无'} · 草稿 ${item.draft_count}`}/></div></article>})}</div>}
  {data&&<div className="pager"><span>第 {data.page} 页 · 共 {data.total} 个事件</span><button disabled={data.page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><button disabled={!data.has_next} onClick={()=>setPage(p=>p+1)}>下一页</button></div>}
 </Panel>
}
