import { useCallback,useEffect,useMemo,useState } from 'react'
import { Empty,ErrorBanner,Panel } from '../components/common'
import { Badge,EventBadge,Metric,RiskBadge,fmt } from '../components/workbench'
import { editorialWorkflowError,type EditorialWorkflowApi } from '../editorialWorkflowApi'
import type { CandidateGenerationInput,CandidateGroup,CandidateListItem,CandidateListResponse,CandidatePreview,CandidateRun,DecisionHistoryItem,EditorialDecisionType } from '../editorialWorkflowTypes'
import type { PublicationApi } from '../publicationApi'
import type { EditorialRisk } from '../workbenchTypes'

const topViews=[20,10,5,3] as const
const decisions:EditorialDecisionType[]=['adopt','watch','drop','archive']
export function EditorialCandidatesPage({api,publicationApi,actorConfigured,onOpenEvent}:{api:EditorialWorkflowApi;publicationApi:PublicationApi;actorConfigured:boolean;onOpenEvent:(id:string)=>void}){
 const[runs,setRuns]=useState<CandidateRun[]>([]),[runId,setRunId]=useState(''),[topN,setTopN]=useState<number>(20),[group,setGroup]=useState<CandidateGroup|''>(''),[risk,setRisk]=useState<EditorialRisk|''>(''),[category,setCategory]=useState(''),[decisionFilter,setDecisionFilter]=useState<EditorialDecisionType|''>(''),[data,setData]=useState<CandidateListResponse|null>(null),[publicationCounts,setPublicationCounts]=useState<Record<string,number>>({}),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null)
 const[selected,setSelected]=useState<CandidateListItem|null>(null),[history,setHistory]=useState<DecisionHistoryItem[]>([]),[decision,setDecision]=useState<EditorialDecisionType>('watch'),[reason,setReason]=useState(''),[riskAck,setRiskAck]=useState(false),[confirmation,setConfirmation]=useState(false)
 const[businessDate,setBusinessDate]=useState(''),[timezone,setTimezone]=useState('Asia/Shanghai'),[asOf,setAsOf]=useState(''),[lookback,setLookback]=useState(24),[limit,setLimit]=useState(20),[preview,setPreview]=useState<CandidatePreview|null>(null)
 const loadRuns=useCallback(async(preferred?:string)=>{try{const rows=await api.runs();setRuns(rows);setRunId(current=>preferred&&rows.some(r=>r.id===preferred)?preferred:current&&rows.some(r=>r.id===current)?current:rows[0]?.id||'')}catch(e){setError(editorialWorkflowError(e))}},[api])
 useEffect(()=>{void loadRuns()},[loadRuns])
 const loadCandidates=useCallback(async()=>{if(!runId){setData(null);return}setLoading(true);setError(null);try{const[candidates,published]=await Promise.all([api.candidates({runId,topN,group:group||undefined,risk:risk||undefined,category:category||undefined}),publicationApi.publicationCounts()]);setData(candidates);setPublicationCounts(published)}catch(e){setError(editorialWorkflowError(e))}finally{setLoading(false)}},[api,publicationApi,runId,topN,group,risk,category])
 useEffect(()=>{void loadCandidates()},[loadCandidates])
 const visible=useMemo(()=>data?.items.filter(item=>!decisionFilter||item.current_editorial_decision?.decision===decisionFilter)||[],[data,decisionFilter])
 const counts=useMemo(()=>{const value={adopt:0,watch:0,drop:0,archive:0};for(const item of data?.items||[]){const current=item.current_editorial_decision?.decision;if(current)value[current]+=1}return value},[data])
 const generation=():CandidateGenerationInput=>({business_date:businessDate||undefined,timezone:timezone||undefined,as_of_at:asOf?new Date(asOf).toISOString():undefined,lookback_hours:lookback,requested_limit:limit})
 const doPreview=async()=>{setError(null);try{setPreview(await api.preview(generation()))}catch(e){setError(editorialWorkflowError(e))}}
 const doApply=async()=>{setError(null);try{const result=await api.apply(generation());setPreview(null);await loadRuns(result.run.id)}catch(e){setError(editorialWorkflowError(e))}}
 const choose=async(item:CandidateListItem)=>{setSelected(item);setDecision(item.current_editorial_decision?.decision||'watch');setReason('');setRiskAck(false);setConfirmation(false);try{setHistory(await api.history(item.candidate.event_id))}catch(e){setError(editorialWorkflowError(e))}}
 const submitDecision=async()=>{if(!selected)return;setError(null);try{await api.decide(selected.candidate.event_id,{candidate_id:selected.candidate.id,decision,expected_previous_decision_id:selected.current_editorial_decision?.id||null,risk_acknowledged:riskAck,reason,confirmation});setReason('');await loadCandidates();setHistory(await api.history(selected.candidate.event_id))}catch(e){setError(editorialWorkflowError(e))}}
 const selectedNeedsRisk=Boolean(selected&&(selected.candidate.effective_risk_level==='R3'||selected.candidate.effective_risk_level==='R4')&&decision==='adopt'),selectedNeedsConfirm=Boolean(selected&&(decision==='archive'||selected.current_editorial_decision?.decision==='archive'))
 return <div className="event-list"><Panel title="Daily Candidates" actions={<button onClick={()=>void loadRuns()}>Refresh</button>}>
  <div className="notice">系统候选排名是 deterministic algorithmic rank；Human Decision、Publication 与 Event lifecycle、rank 完全独立。Adopted ≠ Published；只有 PublicationRecord 才表示真实发布已记录。</div>
  <div className="filter-grid"><label>Run<select aria-label="Candidate Run" value={runId} onChange={e=>setRunId(e.target.value)}><option value="">No run</option>{runs.map(run=><option value={run.id} key={run.id}>{run.business_date} · {fmt(run.as_of_at)} · {run.candidate_count} candidates</option>)}</select></label><label>Group<select aria-label="Candidate group" value={group} onChange={e=>setGroup(e.target.value as CandidateGroup|'')}><option value="">All</option><option value="normal">normal</option><option value="review_required">review_required</option></select></label><label>Risk<select aria-label="Candidate risk" value={risk} onChange={e=>setRisk(e.target.value as EditorialRisk|'')}><option value="">All</option>{['R0','R1','R2','R3','R4'].map(value=><option key={value}>{value}</option>)}</select></label><label>Category<input aria-label="Candidate category" value={category} onChange={e=>setCategory(e.target.value)}/></label></div>
  <div className="actions">{topViews.map(value=><button className={topN===value?'active':''} key={value} onClick={()=>setTopN(value)}>TOP{value}</button>)}<button className={!decisionFilter?'active':''} onClick={()=>setDecisionFilter('')}>All Decisions</button><button className={decisionFilter==='watch'?'active':''} onClick={()=>setDecisionFilter('watch')}>Watchlist {counts.watch}</button><button className={decisionFilter==='adopt'?'active':''} onClick={()=>setDecisionFilter('adopt')}>Adopted {counts.adopt}</button><button className={decisionFilter==='drop'?'active':''} onClick={()=>setDecisionFilter('drop')}>Dropped {counts.drop}</button><button className={decisionFilter==='archive'?'active':''} onClick={()=>setDecisionFilter('archive')}>Archived {counts.archive}</button></div>
  {data&&<div className="metric-grid compact"><Metric label="Business Date" value={data.run.business_date}/><Metric label="As of" value={fmt(data.run.as_of_at)}/><Metric label="Window" value={`${fmt(data.run.window_start_at)} → ${fmt(data.run.window_end_at)}`}/><Metric label="Ranking" value={data.run.ranking_version}/><Metric label="Candidates" value={`${data.run.candidate_count} / ${data.run.eligible_event_count} eligible`}/><Metric label="Generated by" value={data.run.actor}/></div>}
  <ErrorBanner error={error}/>{loading&&<div className="section-state">Loading candidates…</div>}{!loading&&runId&&visible.length===0&&<Empty text="No Candidates match this view"/>}
  {!loading&&visible.map(item=>{const candidate=item.candidate,current=item.current_editorial_decision,published=publicationCounts[candidate.event_id]||0;return <article className="event-row" key={candidate.id||`${candidate.event_id}-${candidate.rank}`}><div className="event-main"><strong>系统候选排名 / Algorithmic Rank #{candidate.rank}</strong><button className="link-button event-title" onClick={()=>onOpenEvent(candidate.event_id)}>{candidate.event_title_snapshot}</button><div className="badges"><EventBadge value={candidate.event_status_snapshot}/>{candidate.category_snapshot&&<Badge>{candidate.category_snapshot}</Badge>}<Badge tone={candidate.candidate_group==='review_required'?'warn':'ok'}>{candidate.candidate_group}</Badge><RiskBadge value={candidate.effective_risk_level}/>{current&&<Badge tone={current.decision==='archive'?'danger':'info'}>Human: {current.decision}</Badge>}{published>0&&<Badge tone="ok">Published · {published}</Badge>}{item.stale_indicator&&<Badge tone="warn">Possibly stale</Badge>}</div><small>Snapshot updated {fmt(candidate.event_last_updated_at_snapshot)} · Context {candidate.candidate_context_hash.slice(0,10)}</small><div className="actions"><button onClick={()=>void choose(item)}>Decision / History</button><button onClick={()=>onOpenEvent(candidate.event_id)}>Open Event Workbench</button></div></div><div className="event-stats"><Metric label="Effective Traffic" value={candidate.effective_traffic_total.toFixed(1)}/><Metric label="Trend update" value={String(candidate.ranking_components.update_value??'Unavailable')}/><Metric label="Signal velocity" value={String(candidate.ranking_components.signal_velocity??'Unavailable')}/><Metric label="Sources / Platforms" value={`${candidate.source_count_snapshot} / ${candidate.platform_count_snapshot}`}/><Metric label="Evidence" value={`${candidate.evidence_summary.total??0} claims`} help={`confirmed ${candidate.evidence_summary.confirmed??0} · disputed ${candidate.evidence_summary.disputed??0}`}/><Metric label="Open Unknowns" value={candidate.open_unknown_count}/><Metric label="Format" value={candidate.recommended_format}/><Metric label="Artifacts" value={`Card ${candidate.card_exists_snapshot?'yes':'no'} · Draft ${candidate.draft_exists_snapshot?'yes':'no'} · Publication ${published>0?published:'no'}`}/></div></article>})}
 </Panel>
 <Panel title="Generate Daily Candidate Pool"><div className="notice">Preview is side-effect free. Apply is deterministic DB processing and requires Actor + explicit confirmation. Candidate generation 不调用 AI，也不会因 Publication/Performance 修改 candidate-ranking-v1。</div><div className="filter-grid"><label>Business date<input aria-label="Business date" type="date" value={businessDate} onChange={e=>setBusinessDate(e.target.value)}/></label><label>Timezone<input aria-label="Business timezone" value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><label>As of<input aria-label="Candidate as of" type="datetime-local" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><label>Lookback hours<input aria-label="Lookback hours" type="number" min={1} max={168} value={lookback} onChange={e=>setLookback(Number(e.target.value))}/></label><label>Limit<input aria-label="Candidate limit" type="number" min={1} max={100} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label></div><div className="actions"><button onClick={()=>void doPreview()}>Preview Pool</button><button disabled={!actorConfigured} onClick={()=>void doApply()}>Apply Pool</button>{!actorConfigured&&<small className="warning-text">Configure Actor ID before Apply.</small>}</div>{preview&&<div className="metric-grid compact"><Metric label="Preview candidates" value={preview.candidate_count}/><Metric label="Eligible" value={preview.eligible_event_count}/><Metric label="Skipped" value={preview.skipped_event_count}/><Metric label="Input hash" value={preview.input_hash.slice(0,12)}/><Metric label="Ranking" value={preview.ranking_version}/><Metric label="As of" value={fmt(preview.as_of_at)}/></div>}</Panel>
 {selected&&<Panel title={`Human Editorial Decision · Rank #${selected.candidate.rank}`} actions={<button onClick={()=>setSelected(null)}>Close</button>}><div className="notice">Decision 不修改 Algorithmic Rank。Adopt 也不会自动生成内容或自动成为 Published；Archive 是唯一默认影响未来候选 eligibility 的决定，并可通过新 Decision 恢复。</div><div className="filter-grid"><label>Decision<select aria-label="Editorial Decision" value={decision} onChange={e=>setDecision(e.target.value as EditorialDecisionType)}>{decisions.map(value=><option key={value}>{value}</option>)}</select></label><label>Reason<textarea aria-label="Decision reason" value={reason} onChange={e=>setReason(e.target.value)}/></label>{selectedNeedsRisk&&<label className="check-field"><input aria-label="Risk acknowledgement" type="checkbox" checked={riskAck} onChange={e=>setRiskAck(e.target.checked)}/> Acknowledge {selected.candidate.effective_risk_level} risk</label>}{selectedNeedsConfirm&&<label className="check-field"><input aria-label="Decision confirmation" type="checkbox" checked={confirmation} onChange={e=>setConfirmation(e.target.checked)}/> Confirm Archive / Restore</label>}</div><button disabled={!actorConfigured||!reason.trim()||(selectedNeedsRisk&&!riskAck)||(selectedNeedsConfirm&&!confirmation)} onClick={()=>void submitDecision()}>Append Human Decision</button><h3>Decision History</h3>{history.length===0?<Empty text="No decision history"/>:<div className="table-wrap"><table><thead><tr><th>Time</th><th>Decision</th><th>Actor</th><th>Reason</th><th>Candidate rank</th><th>Risk</th><th>Run</th></tr></thead><tbody>{history.map(item=><tr key={item.decision.id}><td>{fmt(item.decision.created_at)}</td><td>{item.decision.decision}</td><td>{item.decision.actor}</td><td>{item.decision.reason}</td><td>{item.candidate_rank??'current context'}</td><td>{item.decision.risk_level_snapshot??'—'}</td><td>{item.candidate_run_id?.slice(0,8)??'—'}</td></tr>)}</tbody></table></div>}</Panel>}
 </div>
}
