import { useCallback,useEffect,useState } from 'react'
import { Activity,AlertTriangle,CheckCircle2,CircleHelp,ClipboardCheck,FileStack,Gauge,Send,Sparkles,Target } from 'lucide-react'
import type { AdminApi } from '../api'
import { Empty,ErrorBanner,Panel } from '../components/common'
import { Metric,RiskBadge } from '../components/workbench'
import type { WorkbenchApi } from '../workbenchApi'
import type { WorkbenchOverview } from '../workbenchTypes'
import { eventStatusLabel,validationStatusLabel } from '../uiLabels'

type Readiness={instances:number;accounts:number;sources:number;budgets:number;succeededRuns:number;aiReady:number}
type ProviderSummary={credential_configured:boolean;enabled:boolean}

export function EditorialOverviewPage({api,adminApi,onNavigate}:{api:WorkbenchApi;adminApi:AdminApi;onNavigate:(key:string)=>void}){
 const[data,setData]=useState<WorkbenchOverview|null>(null),[readiness,setReadiness]=useState<Readiness|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const overview=await api.overview();setData(overview);try{const[instances,accounts,sources,budgets,runs,providers]=await Promise.all([adminApi.page<unknown>('/api/v1/admin/connector-instances?page=1&page_size=1'),adminApi.page<unknown>('/api/v1/admin/platform-accounts?page=1&page_size=1'),adminApi.page<unknown>('/api/v1/admin/sources?page=1&page_size=1'),adminApi.page<unknown>('/api/v1/admin/collection-budgets?page=1&page_size=1&enabled=true'),adminApi.page<unknown>('/api/v1/admin/connector-runs?page=1&page_size=1&status=succeeded'),adminApi.page<ProviderSummary>('/api/v1/admin/ai/providers?page=1&page_size=100')]);setReadiness({instances:instances.total,accounts:accounts.total,sources:sources.total,budgets:budgets.total,succeededRuns:runs.total,aiReady:providers.items.filter(item=>item.enabled&&item.credential_configured).length})}catch{setReadiness(null)}}catch(e){setError(e instanceof Error?e.message:'加载编辑总览失败')}finally{setLoading(false)}},[api,adminApi])
 useEffect(()=>{void load()},[load])
 if(loading)return <Panel title="今日编辑总览"><div className="section-state" role="status">正在加载总览…</div></Panel>
 if(error)return <Panel title="今日编辑总览"><ErrorBanner error={error}/><button onClick={()=>void load()}>重试</button></Panel>
 if(!data)return <Panel title="今日编辑总览"><Empty text="暂无总览数据"/></Panel>
 const life=data.lifecycle_counts,h=data.collection_health,a=data.artifact_counts,w=data.candidate_workflow
 const decisions=(w?.current_decision_counts.adopt??0)+(w?.current_decision_counts.watch??0)+(w?.current_decision_counts.drop??0)+(w?.current_decision_counts.archive??0)
 const distribution=[['采用',w?.current_decision_counts.adopt??0,'adopt'],['观察',w?.current_decision_counts.watch??0,'watch'],['放弃',w?.current_decision_counts.drop??0,'drop'],['归档',w?.current_decision_counts.archive??0,'archive']] as const;const distributionTotal=Math.max(1,distribution.reduce((total,[,value])=>total+value,0))
 const workflow=[['候选池',w?.latest_run?.candidate_count??0,ClipboardCheck],['人工判断',decisions,Target],['内容产物',a.event_cards+a.editorial_packs+a.drafts,FileStack],['发布记录',0,Send],['效果回流',0,Activity]] as const
 const setupSteps=readiness?[{label:'配置采集平台',done:readiness.instances>0,page:'instances',help:'创建一个可运行的连接器实例'},{label:'配置平台账号',done:readiness.accounts>0,page:'risk',help:'需要账号的平台绑定专用 Profile'},{label:'创建第一个信源',done:readiness.sources>0,page:'sources',help:'明确搜索关键词、内容 ID 或 Feed'},{label:'设置采集预算',done:readiness.budgets>0,page:'collection-budgets',help:'正式采集量在这里配置'},{label:'完成采集前检查与低量验证',done:readiness.succeededRuns>0,page:'sources',help:'先只读预检，再明确确认真实访问'},{label:'配置 AI 服务',done:readiness.aiReady>0,page:'ai-providers',help:'凭据可用并启用 Provider'},{label:'生成第一批候选',done:Boolean(w?.run_exists),page:'candidates',help:'进入日常编辑工作流'}]:[]
 const nextStep=setupSteps.find(step=>!step.done);const showSetup=Boolean(nextStep)
 return <>
  {showSetup&&<section className="setup-guide"><div className="section-heading"><div><span className="eyebrow">首次使用引导</span><h2>先把第一条“采集 → 编辑”链路跑通</h2><p>不需要先理解所有技术菜单。按下面顺序完成，每一步都会告诉你下一步去哪里。</p></div>{nextStep&&<button className="primary" onClick={()=>onNavigate(nextStep.page)}>下一步：{nextStep.label}</button>}</div><div className="setup-steps">{setupSteps.map((step,index)=><button key={step.label} className={step.done?'done':step===nextStep?'current':''} onClick={()=>onNavigate(step.page)}><span>{step.done?'✓':index+1}</span><div><strong>{step.label}</strong><small>{step.done?'已完成':step.help}</small></div></button>)}</div><div className="notice"><strong>低量验证 ≠ 正式采集量。</strong>真实链路验证单次固定最多 5 条；长期采集的单次、每日与并发数量由“采集预算”配置。</div></section>}
  <section className="overview-hero"><div className="hero-copy"><span className="eyebrow"><Target size={16}/>今日重点关注</span><h1>{w?.run_exists?'候选池已生成':'今日候选池尚未生成'}</h1><p>{w?.run_exists?`${w.latest_run?.candidate_count??0} 条候选 · ${decisions} 条已有编辑判断`:showSetup?'先完成上方首次配置，再生成第一批候选。':'先生成或查看候选快照，再开始人工判断。'}</p></div><div className="hero-actions"><div className="hero-risk"><RiskBadge value={data.high_risk_event_count>0?'R3':'R1'}/><small>{data.high_risk_event_count} 条高风险事件</small></div><button className="primary" onClick={()=>onNavigate('candidates')}>进入今日候选</button></div><div className="hero-visual" aria-hidden="true"><Sparkles className="hero-spark" size={22}/><ClipboardCheck size={58}/></div></section>
  <section className="stat-strip" aria-label="编辑概览统计"><Metric icon={<Gauge size={20}/>} label="活跃事件" value={data.active_event_count} help={`${data.recent_updated_event_count_24h} 条在 24 小时内更新`}/><Metric icon={<Activity size={20}/>} label="今日新增" value={data.recent_new_event_count_24h} help="过去 24 小时"/><Metric icon={<CircleHelp size={20}/>} label="待确认点" value={data.open_unknown_count} help="需要编辑核验"/><Metric icon={<CheckCircle2 size={20}/>} label="已采用" value={w?.current_decision_counts.adopt??0} help="当前候选快照"/><Metric icon={<AlertTriangle size={20}/>} label="高风险" value={data.high_risk_event_count} help="有效风险 R3 / R4"/></section>
  <section className="overview-grid"><div className="overview-section"><div className="section-heading"><div><span className="eyebrow">编辑优先队列</span><h2>从候选快照开始今天的判断</h2></div><button onClick={()=>void load()}>刷新</button></div>{w?.run_exists?<div className="priority-list"><div><span>候选池</span><strong>{w.latest_run?.candidate_count??0} 条可查看</strong><button className="link-button" onClick={()=>onNavigate('candidates')}>打开候选池</button></div><div><span>风险与证据</span><strong>{data.high_risk_event_count} 条高风险 · {data.events_with_evidence_count} 条已有证据</strong><button className="link-button" onClick={()=>onNavigate('events')}>查看事件</button></div><div><span>生命周期</span><strong>{(['emerging','growing','stable','declining','resolved'] as const).map(k=>`${eventStatusLabel[k]} ${life[k]}`).join(' · ')}</strong><span className="muted-text">基于当前事件快照</span></div></div>:<Empty text="今天还没有候选池" helper={showSetup?'先完成首次配置，再进入候选池。':'生成或进入候选池后，这里会显示需要优先处理的编辑事项。'} action={<button onClick={()=>onNavigate(showSetup&&nextStep?nextStep.page:'candidates')}>{showSetup&&nextStep?`下一步：${nextStep.label}`:'进入候选池'}</button>}/>}</div><div className="overview-section situation"><div className="section-heading"><div><span className="eyebrow">今日态势</span><h2>当前编辑决定分布</h2></div></div><div className="decision-distribution">{distribution.map(([label,value,tone])=><div className={`distribution-row ${tone}`} key={label}><span><small>{label}</small><strong>{value}</strong></span><span className="distribution-track"><i style={{width:`${value/distributionTotal*100}%`}}/></span></div>)}</div><p className="muted-text">候选、决定与风险均来自当前 API 的真实快照。</p></div></section>
  <section className="workflow-strip" aria-label="今日工作流">{workflow.map(([label,value,Icon],index)=><div key={label}><span><Icon size={18}/></span><small>{index+1}. {label}</small><strong>{String(value)}</strong></div>)}</section>
  <div className="notice compact-notice"><strong>日常工作流：</strong>总览 → 候选 → 人工判断 → 事件工作台 → 证据 / Card / Pack / Draft → 发布 → 效果反馈。高级配置页面不需要每天操作。</div>
  <div className="wb-two-col"><Panel title="采集与风险健康"><div className="metric-grid compact"><Metric label="24 小时失败运行" value={h.failed_runs_24h}/><Metric label="24 小时风险暂停" value={h.paused_risk_runs_24h}/><Metric label="未处理风险事件" value={h.open_risk_events}/><Metric label="暂停账号" value={h.paused_accounts}/><Metric label="采集检查点" value={h.checkpoint_count}/></div><div className="actions"><button onClick={()=>onNavigate('sources')}>信源 / 采集前检查</button><button onClick={()=>onNavigate('collection-budgets')}>采集预算</button><button onClick={()=>onNavigate('runs')}>运行记录</button><button onClick={()=>onNavigate('risk')}>平台账号 / 风险</button></div></Panel><Panel title="生产 AI 服务验证"><div className="provider-status"><RiskBadge value="R2"/><strong>{validationStatusLabel[data.production_ai_provider_validation]||data.production_ai_provider_validation}</strong></div><p className="muted-text">AI Route 的任务级 max_output_tokens 与 AI Budget 是两层不同约束：前者控制单次生成上限，后者控制成本 / Token 总预算。</p><div className="actions"><button onClick={()=>onNavigate('ai-providers')}>AI 服务商</button><button onClick={()=>onNavigate('ai-routes')}>AI 路由 / 生成上限</button><button onClick={()=>onNavigate('ai-budgets')}>AI 预算</button></div></Panel></div>
 </>
}
