import { useCallback,useEffect,useState } from 'react'
import { Empty,ErrorBanner,Panel } from '../components/common'
import { Badge,EventBadge,FriendlyError,Metric,RiskBadge,fmt } from '../components/workbench'
import { EventCardPackSection } from '../components/editorial/EventCardPackSection'
import { EventDraftsSection } from '../components/editorial/EventDraftsSection'
import { EventEvidenceSection } from '../components/editorial/EventEvidenceSection'
import { EventSourcesSection } from '../components/editorial/EventSourcesSection'
import { EventTrendScoreSection } from '../components/editorial/EventTrendScoreSection'
import type { WorkbenchApi } from '../workbenchApi'
import type { WorkbenchEventDetail } from '../workbenchTypes'

type Tab='overview'|'evidence'|'sources'|'trend'|'card'|'drafts'
const tabs:[Tab,string][]=[['overview','Overview'],['evidence','Evidence'],['sources','Sources & Timeline'],['trend','Trend & Score'],['card','Card & Pack'],['drafts','Drafts']]
export function EventWorkbenchPage({api,eventId,actorConfigured,onBack,onOpenEvent}:{api:WorkbenchApi;eventId:string;actorConfigured:boolean;onBack:()=>void;onOpenEvent:(id:string)=>void}){
 const[data,setData]=useState<WorkbenchEventDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[tab,setTab]=useState<Tab>('overview'),[sourceEventId,setSourceEventId]=useState(''),[mergeReason,setMergeReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await api.event(eventId))}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,eventId]);useEffect(()=>{void load()},[load])
 if(loading)return <Panel title="Event Workbench"><div role="status" className="section-state">Loading Event…</div></Panel>
 if(error&&!data)return <Panel title="Event Workbench"><ErrorBanner error={error}/><button onClick={onBack}>Back to Events</button></Panel>
 if(!data)return <Panel title="Event Workbench"><Empty text="Event unavailable"/></Panel>
 const event=data.event,merged=Boolean(event.merged_into_event_id),canWrite=actorConfigured&&!merged,effective=data.effective_editorial
 const merge=async()=>{if(!sourceEventId.trim()||!mergeReason.trim())return;if(!window.confirm(`Merge source Event ${sourceEventId} into target Event ${event.id}?`))return;try{setError(null);await api.merge(event.id,sourceEventId.trim(),mergeReason.trim());setSourceEventId('');setMergeReason('');await load()}catch(e){setError(FriendlyError(e))}}
 return <><div className="workbench-header"><div><button className="link-button" onClick={onBack}>← Event Explorer</button><div className="badges"><EventBadge value={event.status}/>{event.category&&<Badge>{event.category}</Badge>}{merged&&<Badge tone="danger">MERGED</Badge>}{data.human_override_applied&&<Badge tone="warn">Human Override Applied</Badge>}</div><h1>{event.title}</h1><p>{event.summary||'No Event summary'}</p></div><div className="header-metrics"><Metric label="First seen" value={fmt(event.first_seen_at)}/><Metric label="Last updated" value={fmt(event.last_updated_at)}/><Metric label="Sources / Platforms" value={`${event.source_count} / ${event.platform_count}`}/><Metric label="Effective Score" value={effective?effective.traffic_total.toFixed(1):'Not scored'}/><Metric label="Effective Risk" value={effective?<RiskBadge value={effective.risk_level}/>:'Not scored'}/><Metric label="Recommended format" value={effective?.recommended_format||'Unavailable'}/></div></div>
 {merged&&event.merged_into_event_id&&<div className="error-banner">MERGED source Event. Historical artifacts remain readable; new writes are disabled. Target: <button className="link-button" onClick={()=>onOpenEvent(event.merged_into_event_id!)}>{event.merged_into_event_id}</button></div>}{!actorConfigured&&!merged&&<div className="notice"><strong>Configure Actor ID.</strong> Read operations remain available, but all Human/AI business write actions are disabled.</div>}<ErrorBanner error={error}/>
 <div className="workbench-tabs" role="tablist" aria-label="Event Workbench sections">{tabs.map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='overview'&&<Overview detail={data} canWrite={canWrite} sourceId={sourceEventId} reason={mergeReason} setSource={setSourceEventId} setReason={setMergeReason} merge={()=>void merge()} refresh={()=>void load()}/>} {tab==='evidence'&&<EventEvidenceSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} {tab==='sources'&&<EventSourcesSection api={api} eventId={eventId} latestCard={data.latest_card} canWrite={canWrite} onSplit={()=>void load()}/>} {tab==='trend'&&<EventTrendScoreSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} {tab==='card'&&<EventCardPackSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} {tab==='drafts'&&<EventDraftsSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} </>
}
function Overview({detail,canWrite,sourceId,reason,setSource,setReason,merge,refresh}:{detail:WorkbenchEventDetail;canWrite:boolean;sourceId:string;reason:string;setSource:(v:string)=>void;setReason:(v:string)=>void;merge:()=>void;refresh:()=>void}){const e=detail.event,t=detail.latest_trend,s=detail.effective_editorial;return <><Panel title="10-second Editorial Summary" actions={<button onClick={refresh}>Refresh</button>}><div className="metric-grid"><Metric label="Lifecycle" value={e.status}/><Metric label="Trend" value={t?`${t.new_signal_count} new · ${t.signal_count} total`:'Not calculated'}/><Metric label="Evidence" value={`${detail.evidence_total} Claims`} help={`${detail.evidence_counts.confirmed} confirmed · ${detail.evidence_counts.disputed} disputed · ${detail.evidence_counts.false} false`}/><Metric label="Open Unknowns" value={detail.open_unknown_count}/><Metric label="Effective Score" value={s?s.traffic_total.toFixed(1):'Not scored'}/><Metric label="Risk" value={s?s.risk_level:'Not scored'}/><Metric label="Card / Pack" value={`${detail.latest_card?'Card':'No Event Card'} · ${detail.latest_pack?'Pack':'No Pack'}`}/><Metric label="Drafts" value={`${detail.draft_summary.draft_count} · ${detail.draft_summary.chain_count} chains`}/></div></Panel><Panel title="Human Merge"><p className="muted-text">M3 service remains authoritative. This UI only sends a Human source Event, target Event and required reason.</p><div className="inline-form"><label>Target Event<input readOnly value={e.id}/></label><label>Source Event ID<input value={sourceId} onChange={x=>setSource(x.target.value)}/></label><label>Reason<input value={reason} onChange={x=>setReason(x.target.value)}/></label><button className="danger" disabled={!canWrite||!sourceId.trim()||!reason.trim()} title={!canWrite?'Configure Actor ID or merged Event is read-only':''} onClick={merge}>Merge source into target</button></div></Panel></>}
