import { useCallback,useEffect,useState } from 'react'
import { Empty,ErrorBanner,Panel } from '../components/common'
import { Badge,EventBadge,FriendlyError,Metric,RiskBadge,fmt } from '../components/workbench'
import { EventCardPackSection } from '../components/editorial/EventCardPackSection'
import { EventDraftsSection } from '../components/editorial/EventDraftsSection'
import { EventEvidenceSection } from '../components/editorial/EventEvidenceSection'
import { EventSourcesSection } from '../components/editorial/EventSourcesSection'
import { EventTrendScoreSection } from '../components/editorial/EventTrendScoreSection'
import { editorialWorkflowError,type EditorialWorkflowApi } from '../editorialWorkflowApi'
import type { DecisionHistoryItem,EditorialDecisionType } from '../editorialWorkflowTypes'
import type { WorkbenchApi } from '../workbenchApi'
import type { WorkbenchEventDetail } from '../workbenchTypes'

type Tab='overview'|'evidence'|'sources'|'trend'|'card'|'drafts'
const tabs:[Tab,string][]=[['overview','编辑摘要'],['evidence','证据'],['sources','信源与时间线'],['trend','趋势与评分'],['card','卡片与选题包'],['drafts','草稿']]
const decisionOptions:EditorialDecisionType[]=['adopt','watch','drop','archive']
export function EventWorkbenchPage({api,workflowApi,eventId,actorConfigured,onBack,onOpenEvent}:{api:WorkbenchApi;workflowApi?:EditorialWorkflowApi;eventId:string;actorConfigured:boolean;onBack:()=>void;onOpenEvent:(id:string)=>void}){
 const[data,setData]=useState<WorkbenchEventDetail|null>(null),[history,setHistory]=useState<DecisionHistoryItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[tab,setTab]=useState<Tab>('overview'),[sourceEventId,setSourceEventId]=useState(''),[mergeReason,setMergeReason]=useState(''),[decision,setDecision]=useState<EditorialDecisionType>('watch'),[decisionReason,setDecisionReason]=useState(''),[riskAck,setRiskAck]=useState(false),[decisionConfirmation,setDecisionConfirmation]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[next,decisionHistory]=await Promise.all([api.event(eventId),workflowApi?workflowApi.history(eventId):Promise.resolve([])]);setData(next);setHistory(decisionHistory);setDecision(next.current_editorial_decision?.decision||'watch')}catch(e){setError(FriendlyError(e))}finally{setLoading(false)}},[api,workflowApi,eventId]);useEffect(()=>{void load()},[load])
 if(loading)return <Panel title="Event Workbench"><div role="status" className="section-state">Loading Event…</div></Panel>
 if(error&&!data)return <Panel title="Event Workbench"><ErrorBanner error={error}/><button onClick={onBack}>Back to Events</button></Panel>
 if(!data)return <Panel title="Event Workbench"><Empty text="Event unavailable"/></Panel>
 const event=data.event,merged=Boolean(event.merged_into_event_id),canWrite=actorConfigured&&!merged,effective=data.effective_editorial,currentDecision=data.current_editorial_decision
 const merge=async()=>{if(!sourceEventId.trim()||!mergeReason.trim())return;if(!window.confirm(`Merge source Event ${sourceEventId} into target Event ${event.id}?`))return;try{setError(null);await api.merge(event.id,sourceEventId.trim(),mergeReason.trim());setSourceEventId('');setMergeReason('');await load()}catch(e){setError(FriendlyError(e))}}
 const needsRisk=(effective?.risk_level==='R3'||effective?.risk_level==='R4')&&decision==='adopt',needsConfirmation=decision==='archive'||currentDecision?.decision==='archive'
 const submitDecision=async()=>{if(!workflowApi||!decisionReason.trim())return;try{setError(null);await workflowApi.decide(event.id,{candidate_id:null,decision,expected_previous_decision_id:currentDecision?.id||null,risk_acknowledged:riskAck,reason:decisionReason.trim(),confirmation:decisionConfirmation});setDecisionReason('');setRiskAck(false);setDecisionConfirmation(false);await load()}catch(e){setError(editorialWorkflowError(e))}}
 return <><div className="workbench-header"><div><button className="link-button" onClick={onBack}>← 返回事件列表</button><div className="badges"><EventBadge value={event.status}/>{event.category&&<Badge>{event.category}</Badge>}{merged&&<Badge tone="danger">已合并</Badge>}{data.human_override_applied&&<Badge tone="warn">已人工覆盖</Badge>}{currentDecision&&<Badge tone={currentDecision.decision==='archive'?'danger':'info'}>人工：{currentDecision.decision}</Badge>}{data.latest_candidate&&<Badge>算法排名 #{data.latest_candidate.rank}</Badge>}</div><h1>{event.title}</h1><p>{event.summary||'暂无事件摘要'}</p></div><div className="header-metrics"><Metric label="首次发现" value={fmt(event.first_seen_at)}/><Metric label="最近更新" value={fmt(event.last_updated_at)}/><Metric label="信源 / 平台" value={`${event.source_count} / ${event.platform_count}`}/><Metric label="有效评分" value={effective?effective.traffic_total.toFixed(1):'尚未评分'}/><Metric label="有效风险" value={effective?<RiskBadge value={effective.risk_level}/>:'尚未评分'}/><Metric label="推荐形式" value={effective?.recommended_format||'暂无'}/></div></div>
 {merged&&event.merged_into_event_id&&<div className="error-banner">MERGED source Event. Historical artifacts remain readable; new writes are disabled. Target: <button className="link-button" onClick={()=>onOpenEvent(event.merged_into_event_id!)}>{event.merged_into_event_id}</button></div>}{!actorConfigured&&!merged&&<div className="notice"><strong>Configure Actor ID.</strong> Read operations remain available, but all Human/AI business write actions are disabled.</div>}<ErrorBanner error={error}/>
 <div className="workbench-tabs" role="tablist" aria-label="Event Workbench sections">{tabs.map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='overview'&&<div className="workbench-overview-layout"><main><Overview detail={data} canWrite={canWrite} sourceId={sourceEventId} reason={mergeReason} setSource={setSourceEventId} setReason={setMergeReason} merge={()=>void merge()} refresh={()=>void load()}/></main><aside><Panel title="编辑决策"><div className="notice">生命周期、算法排名与人工判断彼此独立；此处不会自动生成 Card、Pack 或 Draft。</div><div className="rail-health"><span>当前决定：<strong>{currentDecision?.decision||'暂无'}</strong></span><span>算法排名：<strong>{data.latest_candidate?`#${data.latest_candidate.rank}`:'未入选'}</strong></span><span>证据：<strong>{data.evidence_total} 条</strong></span><span>待确认：<strong>{data.open_unknown_count}</strong></span></div>{workflowApi&&<><div className="inline-form"><label>决定<select aria-label="Event Editorial Decision" value={decision} onChange={e=>setDecision(e.target.value as EditorialDecisionType)}>{decisionOptions.map(value=><option key={value}>{value}</option>)}</select></label><label>理由<input aria-label="Event decision reason" value={decisionReason} onChange={e=>setDecisionReason(e.target.value)}/></label>{needsRisk&&<label className="check-field"><input aria-label="Event risk acknowledgement" type="checkbox" checked={riskAck} onChange={e=>setRiskAck(e.target.checked)}/> 确认 {effective?.risk_level} 风险</label>}{needsConfirmation&&<label className="check-field"><input aria-label="Event decision confirmation" type="checkbox" checked={decisionConfirmation} onChange={e=>setDecisionConfirmation(e.target.checked)}/> 确认归档 / 恢复</label>}<button className="primary" disabled={!canWrite||!decisionReason.trim()||(needsRisk&&!riskAck)||(needsConfirmation&&!decisionConfirmation)} onClick={()=>void submitDecision()}>保存人工判断</button></div><details className="decision-history"><summary>决策历史 ({history.length})</summary>{history.length>0&&<div className="table-wrap"><table><thead><tr><th>时间</th><th>决定</th><th>执行者</th><th>理由</th><th>排名</th><th>风险</th></tr></thead><tbody>{history.map(item=><tr key={item.decision.id}><td>{fmt(item.decision.created_at)}</td><td>{item.decision.decision}</td><td>{item.decision.actor}</td><td>{item.decision.reason}</td><td>{item.candidate_rank??'当前上下文'}</td><td>{item.decision.risk_level_snapshot??'—'}</td></tr>)}</tbody></table></div>}</details></>}</Panel></aside></div>} {tab==='evidence'&&<EventEvidenceSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} {tab==='sources'&&<EventSourcesSection api={api} eventId={eventId} latestCard={data.latest_card} canWrite={canWrite} onSplit={()=>void load()}/>} {tab==='trend'&&<EventTrendScoreSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} {tab==='card'&&<EventCardPackSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} {tab==='drafts'&&<EventDraftsSection api={api} eventId={eventId} canWrite={canWrite} onChanged={()=>void load()}/>} </>
}
function Overview({detail,canWrite,sourceId,reason,setSource,setReason,merge,refresh}:{detail:WorkbenchEventDetail;canWrite:boolean;sourceId:string;reason:string;setSource:(v:string)=>void;setReason:(v:string)=>void;merge:()=>void;refresh:()=>void}){const e=detail.event,t=detail.latest_trend,s=detail.effective_editorial;return <><Panel title="10-second Editorial Summary" actions={<button onClick={refresh}>Refresh</button>}><div className="metric-grid"><Metric label="Lifecycle" value={e.status}/><Metric label="Trend" value={t?`${t.new_signal_count} new · ${t.signal_count} total`:'Not calculated'}/><Metric label="Evidence" value={`${detail.evidence_total} Claims`} help={`${detail.evidence_counts.confirmed} confirmed · ${detail.evidence_counts.disputed} disputed · ${detail.evidence_counts.false} false`}/><Metric label="Open Unknowns" value={detail.open_unknown_count}/><Metric label="Effective Score" value={s?s.traffic_total.toFixed(1):'Not scored'}/><Metric label="Risk" value={s?s.risk_level:'Not scored'}/><Metric label="Card / Pack" value={`${detail.latest_card?'Card':'No Event Card'} · ${detail.latest_pack?'Pack':'No Pack'}`}/><Metric label="Drafts" value={`${detail.draft_summary.draft_count} · ${detail.draft_summary.chain_count} chains`}/></div></Panel><Panel title="Human Merge"><p className="muted-text">M3 service remains authoritative. This UI only sends a Human source Event, target Event and required reason.</p><div className="inline-form"><label>Target Event<input readOnly value={e.id}/></label><label>Source Event ID<input value={sourceId} onChange={x=>setSource(x.target.value)}/></label><label>Reason<input value={reason} onChange={x=>setReason(x.target.value)}/></label><button className="danger" disabled={!canWrite||!sourceId.trim()||!reason.trim()} title={!canWrite?'Configure Actor ID or merged Event is read-only':''} onClick={merge}>Merge source into target</button></div></Panel></>}
