import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { AdminApi } from '../api'
import { WorkbenchApi } from '../workbenchApi'
import { EventWorkbenchPage } from './EventWorkbenchPage'

const id='11111111-1111-4111-8111-111111111111'
const claim=(state:string,i:number)=>({id:`20000000-0000-4000-8000-00000000000${i}`,event_id:id,claim_text:`${state} claim`,claim_type:'fact',verification_state:state,extraction_confidence:.8,claim_fingerprint:`f${i}`,extraction_version:'v1',extraction_run_id:null,ai_invocation_id:null,created_by_type:'human',created_by_actor:'editor',editor_note:null,created_at:'2026-08-09T08:00:00Z',updated_at:'2026-08-09T09:00:00Z',sources:[{signal_id:`30000000-0000-4000-8000-00000000000${i}`,role:state==='false'?'contradicting':'supporting',title:`Source ${state}`,platform:'rss',author_name:'author',published_at:'2026-08-09T08:30:00Z',collected_at:'2026-08-09T08:40:00Z',original_url:'https://example.com/source',canonical_url:'https://example.com/source'}]})
const claims=['confirmed','investigating','single_source','disputed','false'].map(claim)
const trend={id:'50000000-0000-4000-8000-000000000001',event_id:id,calculation_version:'v1',window_start_at:'2026-08-09T08:00:00Z',window_end_at:'2026-08-09T10:00:00Z',signal_count:5,new_signal_count:2,source_count:3,platform_count:2,signal_velocity:1.2,interaction_velocity:null,cross_source:true,cross_platform:true,semantic_novelty:null,cn_gap:null,update_value:50,feature_availability:{signal_velocity:true,interaction_velocity:false,semantic_novelty:false,cn_gap:false,media_availability:false,update_value:true},component_metrics:{unavailable_reasons:{interaction_velocity:'INTERACTION_NORMALIZATION_UNAVAILABLE',semantic_novelty:'EVENT_SEMANTIC_NOVELTY_UNAVAILABLE',cn_gap:'GEOGRAPHY_CLASSIFICATION_UNAVAILABLE',media_availability:'MEDIA_CLASSIFICATION_UNAVAILABLE'}},input_hash:'b'.repeat(64),created_at:'2026-08-09T10:00:00Z'}
const score={id:'40000000-0000-4000-8000-000000000001',event_id:id,trend_snapshot_id:trend.id,score_template:'general',score_template_version:'v1',scoring_version:'v1',source_type:'ai',emotion:60,information_gap:70,visual_value:50,user_relevance:75,discussion:65,novelty:55,extendability:70,traffic_total:64,risk_level:'R3',recommended_format:'quick_explainer',model_reason:'AI reason',ai_invocation_id:'60000000-0000-4000-8000-000000000001',scoring_run_id:null,input_hash:'a'.repeat(64),created_by_actor:'ai',source_reason:null,created_at:'2026-08-09T09:00:00Z'}
const card={id:'80000000-0000-4000-8000-000000000001',event_id:id,card_version:'event-card-v1',evidence_snapshot_hash:'c'.repeat(64),trend_snapshot_id:trend.id,editorial_score_id:score.id,title:'Card title',concise_summary:'Card summary',timeline:[{time:'2026-08-09T08:00:00Z',text:'Card timeline item'}],confirmed_claim_ids:[claims[0].id],investigating_claim_ids:[claims[1].id],single_source_claim_ids:[claims[2].id],disputed_claim_ids:[claims[3].id],false_claim_ids:[claims[4].id],unknown_ids:['u1'],source_summary:{count:5},effective_assessment:{traffic_total:68},risk_level:'R3',recommended_format:'quick_explainer',generated_by:'deterministic',ai_invocation_id:null,input_hash:'d'.repeat(64),created_at:'2026-08-09T10:05:00Z'}
const pack={id:'90000000-0000-4000-8000-000000000001',event_id:id,event_card_id:card.id,pack_version:'editorial-pack-v1',recommended_format:'quick_explainer',suggested_angles:[{title:'Angle'}],source_items:[],timeline_items:[],material_items:[],warnings:[{code:'MEDIA_METADATA_UNAVAILABLE'}],unknown_items:[],claim_references:[],input_hash:'e'.repeat(64),ai_invocation_id:null,created_at:'2026-08-09T10:06:00Z'}
const event={id,title:'Workbench Event',summary:'Summary',category:'social',status:'growing',first_seen_at:'2026-08-09T08:00:00Z',last_updated_at:'2026-08-09T10:00:00Z',primary_language:'zh',entities:[],keywords:[],source_count:5,platform_count:2,merged_into_event_id:null,created_at:'2026-08-09T08:00:00Z',updated_at:'2026-08-09T10:00:00Z'}
const detail={event,latest_trend:trend,latest_ai_score:score,latest_human_score:null,effective_editorial:{emotion:80,information_gap:70,visual_value:50,user_relevance:75,discussion:65,novelty:55,extendability:70,traffic_total:68,risk_level:'R3',recommended_format:'quick_explainer',model_reason:'effective',base_score_id:score.id,base_source_type:'ai'},human_override_applied:true,applied_override_count:1,evidence_counts:{confirmed:1,investigating:1,single_source:1,disputed:1,false:1},evidence_total:5,open_unknown_count:1,card_count:1,latest_card:card,latest_card_id:card.id,latest_pack:pack,draft_count:2,latest_draft_id:'d2',signal_summary:{total:5,by_relation:{origin:1,report:4}},draft_summary:{draft_count:2,chain_count:1,latest_draft_id:'d2'}}
const draft=(version:number,source_type:'ai'|'human')=>({id:`a0000000-0000-4000-8000-00000000000${version}`,event_id:id,event_card_id:card.id,editorial_pack_id:pack.id,draft_chain_id:'a1000000-0000-4000-8000-000000000001',draft_type:'standard_90s',format_key:'quick_explainer',duration_target_seconds:90,language:'zh',draft_version:version,parent_draft_id:version===1?null:'a0000000-0000-4000-8000-000000000001',source_type,status:source_type==='ai'?'generated':'edited',title:`Draft v${version}`,title_candidates:[],hook:null,hook_candidates:[],cover_text_candidates:[],sections:[],body:`Body v${version}`,ending:null,interaction_question:null,prompt_version:null,schema_version:null,ai_invocation_id:source_type==='ai'?'a2000000-0000-4000-8000-000000000001':null,generation_run_id:null,input_hash:'f'.repeat(64),created_by_actor:source_type==='human'?'editor':null,change_note:null,created_at:`2026-08-09T10:0${version}:00Z`})

function makeApi(calls:Array<{url:string;method:string;body:string}>,stale=false){vi.stubGlobal('fetch',vi.fn(async(raw:string|URL|Request,init:RequestInit={})=>{const url=String(raw),method=init.method||'GET';calls.push({url,method,body:String(init.body||'')});if(url.includes('/workbench/events/')&&url.endsWith(id))return Response.json(detail);if(url.includes('/workbench/events/')&&url.includes('/signals'))return Response.json({items:[{event_signal_id:'slink',signal_id:'s1',relation:'origin',confidence:1,attached_by:'human',platform:'rss',source_id:'src',source_name:'Source',source_type:'rss',author_name:'author',published_at:'2026-08-09T08:00:00Z',collected_at:'2026-08-09T08:01:00Z',effective_at:'2026-08-09T08:00:00Z',title:'Signal title',original_url:'https://example.com/signal',canonical_url:'https://example.com/signal'}],page:1,page_size:50,total:1,has_next:false});if(url.endsWith('/evidence'))return Response.json({event_id:id,claims,unknowns:[{id:'u1',event_id:id,unknown_text:'Open question',unknown_fingerprint:'u',status:'open',source_type:'human',extraction_run_id:null,ai_invocation_id:null,resolved_by_claim_id:null,resolution_note:null,created_by_actor:'editor',created_at:'2026-08-09T09:00:00Z',updated_at:'2026-08-09T09:00:00Z'}]});if(url.endsWith('/editorial-scores/effective'))return Response.json({event_id:id,latest_ai_score:score,latest_human_score:null,effective_base_score_id:score.id,effective_values:{...detail.effective_editorial},applied_overrides:[{id:'o1',editorial_score_id:score.id,overridden_fields:{emotion:80},reason:'human correction',actor:'editor',created_at:'2026-08-09T09:30:00Z'}]});if(url.endsWith('/editorial-scores'))return Response.json([score]);if(url.endsWith('/cards'))return Response.json([card]);if(url.endsWith('/editorial-packs'))return Response.json([pack]);if(url.endsWith('/drafts'))return Response.json([draft(2,'human'),draft(1,'ai')]);if(/\/drafts\/a0/.test(url))return Response.json({draft:draft(2,'human'),claim_references:[],version_chain:[draft(1,'ai'),draft(2,'human')]});if(url.endsWith('/drafts/preview')&&method==='POST'){if(stale)return Response.json({error:{code:'STALE_EDITORIAL_CONTEXT',message:'stale'}},{status:409});return Response.json({run_id:'run',ai_invocation_id:'inv',mode:'preview',status:'succeeded',draft:null,candidate:null,reused:false})}return Response.json({id:'ok',new_event_id:'new-event'})}));return new WorkbenchApi(new AdminApi({apiBaseUrl:'http://api',adminToken:'token',actorId:'editor'}))}
afterEach(()=>vi.unstubAllGlobals())

it('renders evidence, sources, unavailable Trend, effective score, Card/Pack and Draft provenance',async()=>{const calls:Array<{url:string;method:string;body:string}>=[];render(<EventWorkbenchPage api={makeApi(calls)} eventId={id} actorConfigured={false} onBack={()=>undefined} onOpenEvent={()=>undefined}/>);await screen.findByText('Workbench Event');expect(screen.getByText('Human Override Applied')).toBeInTheDocument();expect(screen.getByText(/Configure Actor ID/)).toBeInTheDocument();await userEvent.click(screen.getByRole('tab',{name:'Evidence'}));await screen.findByText('confirmed claim');expect(screen.getByText('single_source claim')).toBeInTheDocument();expect(screen.getByText('false claim')).toBeInTheDocument();await userEvent.click(screen.getAllByRole('button',{name:'Sources & actions'})[0]);const link=screen.getByRole('link',{name:'Source confirmed'});expect(link).toHaveAttribute('target','_blank');expect(link).toHaveAttribute('rel','noopener noreferrer');await userEvent.click(screen.getByRole('tab',{name:'Trend & Score'}));await screen.findByText('Original AI Score');expect(screen.getAllByText(/Unavailable/).length).toBeGreaterThan(0);expect(screen.getByText('Effective Score')).toBeInTheDocument();expect(screen.getByText(/human correction/)).toBeInTheDocument();await userEvent.click(screen.getByRole('tab',{name:'Card & Pack'}));await screen.findByText('Card title');expect(screen.getByText(/MEDIA_METADATA_UNAVAILABLE/)).toBeInTheDocument();await userEvent.click(screen.getByRole('tab',{name:'Drafts'}));await screen.findByText(/Draft chains/);expect(screen.getByText('AI')).toBeInTheDocument();expect(screen.getByText('HUMAN')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Preview Draft'})).toBeDisabled();expect(screen.queryByText(/raw_payload|credential_ref|Authorization|api_key/i)).toBeNull()})

it('requires R3 approval before AI preview and surfaces stale context once',async()=>{const calls:Array<{url:string;method:string;body:string}>=[];render(<EventWorkbenchPage api={makeApi(calls,true)} eventId={id} actorConfigured onBack={()=>undefined} onOpenEvent={()=>undefined}/>);await screen.findByText('Workbench Event');await userEvent.click(screen.getByRole('tab',{name:'Drafts'}));await screen.findByText(/AI Draft Preview/);const preview=screen.getByRole('button',{name:'Preview Draft'});expect(preview).toBeDisabled();await userEvent.type(screen.getByLabelText('R3 Human approval reason'),'editor approved risk');expect(preview).toBeEnabled();await userEvent.click(preview);await screen.findByText('上下文已变化，请刷新后重新生成。');expect(calls.filter(c=>c.url.endsWith('/drafts/preview')&&c.method==='POST')).toHaveLength(1)})

it('uses existing merge and split APIs with confirmation, reason and signal selection',async()=>{const calls:Array<{url:string;method:string;body:string}>=[];vi.stubGlobal('confirm',vi.fn(()=>true));render(<EventWorkbenchPage api={makeApi(calls)} eventId={id} actorConfigured onBack={()=>undefined} onOpenEvent={()=>undefined}/>);await screen.findByText('Workbench Event');await userEvent.type(screen.getByLabelText('Source Event ID'),'22222222-2222-4222-8222-222222222222');await userEvent.type(screen.getByLabelText('Reason'),'same real event');await userEvent.click(screen.getByRole('button',{name:'Merge source into target'}));await waitFor(()=>expect(calls.some(c=>c.url.endsWith(`/events/${id}/merge`)&&c.method==='POST')).toBe(true));await userEvent.click(screen.getByRole('tab',{name:'Sources & Timeline'}));await screen.findByText('Signal title');await userEvent.click(screen.getByRole('checkbox',{name:'Select signal'}));await userEvent.type(screen.getByLabelText('Reason'),'separate signal');await userEvent.click(screen.getByRole('button',{name:'Split selected signals'}));await waitFor(()=>expect(calls.some(c=>c.url.endsWith(`/events/${id}/split`)&&c.method==='POST')).toBe(true))})
