import {useCallback,useEffect,useState} from 'react'
import {Empty,ErrorBanner,Panel} from '../components/common'
import {Metric,fmt} from '../components/workbench'
import {decisionLabel,performanceHorizonLabel} from '../uiLabels'
import {PERFORMANCE_CSV_HEADER,publicationError,type PublicationApi} from '../publicationApi'
import type {ManualPerformanceInput,PerformanceImportPreview,PerformanceOverview,PerformanceTimelineItem,PublicationListResponse} from '../publicationTypes'

const numberOrNull=(value:string)=>value.trim()===''?null:Number(value)
export function PerformancePage({api,actorConfigured}:{api:PublicationApi;actorConfigured:boolean}){
 const[overview,setOverview]=useState<PerformanceOverview|null>(null),[publications,setPublications]=useState<PublicationListResponse|null>(null),[platform,setPlatform]=useState(''),[selected,setSelected]=useState(''),[timeline,setTimeline]=useState<PerformanceTimelineItem[]>([]),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true)
 const[observed,setObserved]=useState(''),[horizon,setHorizon]=useState<ManualPerformanceInput['horizon']>('custom'),[views,setViews]=useState(''),[completion,setCompletion]=useState(''),[watch,setWatch]=useState(''),[likes,setLikes]=useState(''),[comments,setComments]=useState(''),[shares,setShares]=useState(''),[favorites,setFavorites]=useState(''),[followers,setFollowers]=useState('')
 const[csvText,setCsvText]=useState(''),[fileName,setFileName]=useState(''),[preview,setPreview]=useState<PerformanceImportPreview|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[o,p]=await Promise.all([api.overview({platform_key:platform||undefined}),api.publications({platform_key:platform||undefined,page_size:100})]);setOverview(o);setPublications(p)}catch(e){setError(publicationError(e))}finally{setLoading(false)}},[api,platform]);useEffect(()=>{void load()},[load])
 const loadTimeline=async(id:string)=>{setSelected(id);if(!id){setTimeline([]);return}try{setTimeline(await api.timeline(id))}catch(e){setError(publicationError(e))}}
 const addManual=async()=>{if(!selected)return;try{await api.manual(selected,{observed_at:new Date(observed).toISOString(),horizon,views:numberOrNull(views),completion_rate_percent:numberOrNull(completion),average_watch_seconds:numberOrNull(watch),likes:numberOrNull(likes),comments:numberOrNull(comments),shares:numberOrNull(shares),favorites:numberOrNull(favorites),follower_delta:numberOrNull(followers)});await loadTimeline(selected);await load()}catch(e){setError(publicationError(e))}}
 const chooseFile=async(file:File|undefined)=>{if(!file)return;setFileName(file.name);setCsvText(await file.text());setPreview(null)}
 const previewCsv=async()=>{try{setPreview(await api.preview(csvText))}catch(e){setError(publicationError(e))}}
 const applyCsv=async()=>{try{await api.apply(csvText,fileName);setPreview(await api.preview(csvText));await load()}catch(e){setError(publicationError(e))}}
 const downloadTemplate=()=>{const blob=new Blob([`${PERFORMANCE_CSV_HEADER}\n`],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='performance-csv-v1-template.csv';a.click();URL.revokeObjectURL(url)}
 const canManual=Boolean(actorConfigured&&selected&&observed&&[views,completion,watch,likes,comments,shares,favorites,followers].some(v=>v.trim()!==''))
 return <div className="event-list performance-page">
  <Panel title="效果反馈" actions={<button onClick={()=>void load()}>刷新</button>}>
   <div className="page-intro"><p>查看已发布内容的播放与互动表现。效果数据只用于观察，不会修改候选排名、人工决定、编辑评分或证据。</p></div>
   <label>平台筛选<input aria-label="Performance platform filter" value={platform} onChange={e=>setPlatform(e.target.value)} placeholder="输入平台标识"/></label><ErrorBanner error={error}/>
   {overview&&<div className="stat-strip"><Metric label="候选" value={overview.candidate_count}/><Metric label="已采用" value={overview.adopted_count}/><Metric label="已发布" value={overview.published_count}/><Metric label="已有表现数据" value={overview.with_performance_count}/><Metric label="数据新鲜度" value={overview.latest_observed_at?fmt(overview.latest_observed_at):'暂无表现数据'}/></div>}
   {loading&&<div className="section-state">正在加载效果数据…</div>}{!loading&&publications?.items.length===0&&<Empty text="暂无表现数据"/>}
   {publications&&publications.items.length>0&&<div className="table-wrap"><table><thead><tr><th>事件</th><th>平台</th><th>候选排名</th><th>人工决定</th><th>Draft</th><th>播放量</th><th>完播率</th><th>点赞数</th><th>观察时间</th><th>操作</th></tr></thead><tbody>{publications.items.map(item=>{const p=item.publication,s=item.latest_performance?.snapshot;return <tr key={p.id}><td>{item.event_title}</td><td>{p.platform_key}</td><td>{p.candidate_rank_snapshot??'暂无'}</td><td>{p.editorial_decision_snapshot?decisionLabel[p.editorial_decision_snapshot]||p.editorial_decision_snapshot:'暂无'}</td><td>{p.draft_version_snapshot?`v${p.draft_version_snapshot}`:'暂无'}</td><td>{s?.views??'暂无'}</td><td>{s?.completion_rate!=null?`${(s.completion_rate*100).toFixed(1)}%`:'暂无'}</td><td>{s?.likes??'暂无'}</td><td>{s?fmt(s.observed_at):'暂无表现数据'}</td><td><button onClick={()=>void loadTimeline(p.id)}>查看时间线 / 记录表现</button></td></tr>})}</tbody></table></div>}
  </Panel>
  <Panel title="记录表现">
   <div className="page-intro"><p>为一条已发布内容记录某个观察时点的播放和互动表现。</p></div>
   <section className="form-section"><h3>观察信息</h3><div className="form-grid"><label>发布记录<select aria-label="Performance Publication" value={selected} onChange={e=>void loadTimeline(e.target.value)}><option value="">选择发布记录</option>{publications?.items.map(item=><option key={item.publication.id} value={item.publication.id}>{item.event_title} · {item.publication.platform_key} · {fmt(item.publication.published_at)}</option>)}</select></label><label>观察时间<input aria-label="Observed at" type="datetime-local" value={observed} onChange={e=>setObserved(e.target.value)}/></label><label>观察周期<select value={horizon} onChange={e=>setHorizon(e.target.value as ManualPerformanceInput['horizon'])}>{Object.entries(performanceHorizonLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div></section>
   <section className="form-section"><h3>播放表现</h3><div className="form-grid"><label>播放量<input aria-label="Views" type="number" value={views} onChange={e=>setViews(e.target.value)}/></label><label>完播率（%）<input aria-label="Completion %" type="number" value={completion} onChange={e=>setCompletion(e.target.value)}/></label><label>平均观看时长（秒）<input aria-label="Average watch seconds" type="number" value={watch} onChange={e=>setWatch(e.target.value)}/></label></div></section>
   <section className="form-section"><h3>互动表现</h3><div className="form-grid"><label>点赞数<input aria-label="Likes" type="number" value={likes} onChange={e=>setLikes(e.target.value)}/></label><label>评论数<input aria-label="Comments" type="number" value={comments} onChange={e=>setComments(e.target.value)}/></label><label>分享数<input aria-label="Shares" type="number" value={shares} onChange={e=>setShares(e.target.value)}/></label><label>收藏数<input aria-label="Favorites" type="number" value={favorites} onChange={e=>setFavorites(e.target.value)}/></label><label>粉丝变化<input aria-label="Follower delta" type="number" value={followers} onChange={e=>setFollowers(e.target.value)}/></label></div></section>
   <button className="primary" disabled={!canManual} onClick={()=>void addManual()}>保存表现快照</button>{!actorConfigured&&<small className="warning-text">配置 Actor ID 后才能写入表现数据。</small>}
   {selected&&<details className="decision-history"><summary>表现时间线 ({timeline.length})</summary>{timeline.length===0?<Empty text="暂无表现数据"/>:<div className="table-wrap"><table><thead><tr><th>观察时间</th><th>周期</th><th>播放量</th><th>完播率</th><th>点赞</th><th>评论</th><th>分享</th><th>记录时间</th></tr></thead><tbody>{timeline.map(item=><tr key={item.snapshot.id} className={item.is_effective?'':'muted-text'}><td>{fmt(item.snapshot.observed_at)}</td><td>{performanceHorizonLabel[item.snapshot.horizon]||item.snapshot.horizon}</td><td>{item.snapshot.views??'暂无'}</td><td>{item.snapshot.completion_rate!=null?`${(item.snapshot.completion_rate*100).toFixed(1)}%`:'暂无'}</td><td>{item.snapshot.likes??'暂无'}</td><td>{item.snapshot.comments??'暂无'}</td><td>{item.snapshot.shares??'暂无'}</td><td>{fmt(item.snapshot.created_at)}</td></tr>)}</tbody></table></div>}</details>}
  </Panel>
  <Panel title="CSV 导入 · performance-csv-v1"><div className="notice">先预览并查看校验摘要，再确认导入。预览无副作用；存在校验错误时不能导入；导入采用全量成功或全量失败。</div><div className="actions"><button onClick={downloadTemplate}>下载 CSV 模板</button><label className="file-action">选择文件<input aria-label="Performance CSV file" type="file" accept=".csv,text/csv" onChange={e=>void chooseFile(e.target.files?.[0])}/></label><button disabled={!csvText} onClick={()=>void previewCsv()}>预览</button><button className="primary" disabled={!actorConfigured||!preview||preview.invalid_rows>0||preview.errors.length>0} onClick={()=>void applyCsv()}>确认导入</button></div>{preview&&<><div className="stat-strip compact"><Metric label="有效行" value={preview.valid_rows}/><Metric label="无效行" value={preview.invalid_rows}/><Metric label="重复行" value={preview.duplicate_rows}/><Metric label="映射版本" value={preview.mapping_version}/></div>{preview.errors.length>0&&<div className="table-wrap"><table><thead><tr><th>行</th><th>字段</th><th>错误码</th><th>说明</th></tr></thead><tbody>{preview.errors.slice(0,20).map((e,index)=><tr key={`${e.row_number}-${e.field}-${index}`}><td>{e.row_number}</td><td>{e.field}</td><td>{e.code}</td><td>{e.message}</td></tr>)}</tbody></table></div>}</>}</Panel>
 </div>
}
