import {useCallback,useEffect,useState} from 'react'
import {Empty,ErrorBanner,Panel} from '../components/common'
import {Metric,fmt} from '../components/workbench'
import {PERFORMANCE_CSV_HEADER,publicationError,type PublicationApi} from '../publicationApi'
import type {ManualPerformanceInput,PerformanceImportPreview,PerformanceOverview,PerformanceTimelineItem,PublicationListResponse} from '../publicationTypes'

const numberOrNull=(value:string)=>value.trim()===''?null:Number(value)
export function PerformancePage({api,actorConfigured}:{api:PublicationApi;actorConfigured:boolean}){
 const[overview,setOverview]=useState<PerformanceOverview|null>(null),[publications,setPublications]=useState<PublicationListResponse|null>(null),[platform,setPlatform]=useState(''),[selected,setSelected]=useState(''),[timeline,setTimeline]=useState<PerformanceTimelineItem[]>([]),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true)
 const[observed,setObserved]=useState(''),[horizon,setHorizon]=useState<ManualPerformanceInput['horizon']>('custom'),[views,setViews]=useState(''),[completion,setCompletion]=useState(''),[watch,setWatch]=useState(''),[likes,setLikes]=useState(''),[comments,setComments]=useState(''),[shares,setShares]=useState(''),[favorites,setFavorites]=useState(''),[followers,setFollowers]=useState('')
 const[csvText,setCsvText]=useState(''),[fileName,setFileName]=useState(''),[preview,setPreview]=useState<PerformanceImportPreview|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[o,p]=await Promise.all([api.overview({platform_key:platform||undefined}),api.publications({platform_key:platform||undefined,page_size:100})]);setOverview(o);setPublications(p)}catch(e){setError(publicationError(e))}finally{setLoading(false)}},[api,platform]);useEffect(()=>{void load()},[load])
 const loadTimeline=async(id:string)=>{setSelected(id);try{setTimeline(await api.timeline(id))}catch(e){setError(publicationError(e))}}
 const addManual=async()=>{if(!selected)return;try{await api.manual(selected,{observed_at:new Date(observed).toISOString(),horizon,views:numberOrNull(views),completion_rate_percent:numberOrNull(completion),average_watch_seconds:numberOrNull(watch),likes:numberOrNull(likes),comments:numberOrNull(comments),shares:numberOrNull(shares),favorites:numberOrNull(favorites),follower_delta:numberOrNull(followers)});await loadTimeline(selected);await load()}catch(e){setError(publicationError(e))}}
 const chooseFile=async(file:File|undefined)=>{if(!file)return;setFileName(file.name);const text=await file.text();setCsvText(text);setPreview(null)}
 const previewCsv=async()=>{try{setPreview(await api.preview(csvText))}catch(e){setError(publicationError(e))}}
 const applyCsv=async()=>{try{await api.apply(csvText,fileName);setPreview(await api.preview(csvText));await load()}catch(e){setError(publicationError(e))}}
 const downloadTemplate=()=>{const blob=new Blob([`${PERFORMANCE_CSV_HEADER}\n`],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='performance-csv-v1-template.csv';a.click();URL.revokeObjectURL(url)}
 const canManual=actorConfigured&&selected&&observed&&[views,completion,watch,likes,comments,shares,favorites,followers].some(v=>v.trim()!=='')
 return <div className="event-list"><Panel title="Performance Feedback" actions={<button onClick={()=>void load()}>Refresh</button>}><div className="notice">只读 observational feedback。Performance 不会修改 Candidate Rank、Human Decision、Editorial Score、Evidence 或 Prompt，也不做跨平台胜负评分。</div><label>Platform filter<input aria-label="Performance platform filter" value={platform} onChange={e=>setPlatform(e.target.value)}/></label><ErrorBanner error={error}/>{overview&&<div className="metric-grid"><Metric label="Candidates" value={overview.candidate_count}/><Metric label="Adopted" value={overview.adopted_count}/><Metric label="Published" value={overview.published_count}/><Metric label="With performance" value={overview.with_performance_count}/><Metric label="Data freshness" value={overview.latest_observed_at?fmt(overview.latest_observed_at):'No performance data'}/></div>}{loading&&<div className="section-state">Loading performance…</div>}{!loading&&publications?.items.length===0&&<Empty text="No performance data"/>}{publications&&<div className="table-wrap"><table><thead><tr><th>Event</th><th>Platform</th><th>Rank</th><th>Human</th><th>Draft</th><th>Views</th><th>Completion</th><th>Likes</th><th>Observed at</th><th/></tr></thead><tbody>{publications.items.map(item=>{const p=item.publication,s=item.latest_performance?.snapshot;return <tr key={p.id}><td>{item.event_title}</td><td>{p.platform_key}</td><td>{p.candidate_rank_snapshot??'Unavailable'}</td><td>{p.editorial_decision_snapshot??'Unavailable'}</td><td>{p.draft_version_snapshot?`v${p.draft_version_snapshot}`:'Unavailable'}</td><td>{s?.views??'Unavailable'}</td><td>{s?.completion_rate!=null?`${(s.completion_rate*100).toFixed(1)}%`:'Unavailable'}</td><td>{s?.likes??'Unavailable'}</td><td>{s?fmt(s.observed_at):'No performance data'}</td><td><button onClick={()=>void loadTimeline(p.id)}>Timeline / Enter metrics</button></td></tr>})}</tbody></table></div>}</Panel>
 <Panel title="Manual Performance Entry"><div className="notice">空输入保存为 NULL；真实输入 0 才是 0。Completion Rate 在界面输入百分比 0..100，后端正规化到 0..1。</div><div className="filter-grid"><label>Publication<select aria-label="Performance Publication" value={selected} onChange={e=>void loadTimeline(e.target.value)}><option value="">Select Publication</option>{publications?.items.map(item=><option key={item.publication.id} value={item.publication.id}>{item.event_title} · {item.publication.platform_key} · {fmt(item.publication.published_at)}</option>)}</select></label><label>Observed at<input aria-label="Observed at" type="datetime-local" value={observed} onChange={e=>setObserved(e.target.value)}/></label><label>Horizon<select value={horizon} onChange={e=>setHorizon(e.target.value as ManualPerformanceInput['horizon'])}><option>h1</option><option>h24</option><option>d7</option><option>custom</option></select></label>{[['Views',views,setViews],['Completion %',completion,setCompletion],['Average watch seconds',watch,setWatch],['Likes',likes,setLikes],['Comments',comments,setComments],['Shares',shares,setShares],['Favorites',favorites,setFavorites],['Follower delta',followers,setFollowers]].map(([label,value,setter])=><label key={label as string}>{label as string}<input aria-label={label as string} type="number" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}</div><button disabled={!canManual} onClick={()=>void addManual()}>Record Performance Snapshot</button>{!actorConfigured&&<small className="warning-text">Configure Actor ID before writing metrics.</small>}{selected&&<><h3>Performance Timeline</h3>{timeline.length===0?<Empty text="No performance data"/>:<div className="table-wrap"><table><thead><tr><th>Observed</th><th>Horizon</th><th>Views</th><th>Completion</th><th>Avg watch</th><th>Likes</th><th>Comments</th><th>Shares</th><th>Favorites</th><th>Followers</th><th>Source</th><th>Recorded</th></tr></thead><tbody>{timeline.map(item=><tr key={item.snapshot.id} className={item.is_effective?'':'muted-text'}><td>{fmt(item.snapshot.observed_at)}</td><td>{item.snapshot.horizon}</td><td>{item.snapshot.views??'Unavailable'}</td><td>{item.snapshot.completion_rate!=null?`${(item.snapshot.completion_rate*100).toFixed(1)}%`:'Unavailable'}</td><td>{item.snapshot.average_watch_seconds??'Unavailable'}</td><td>{item.snapshot.likes??'Unavailable'}</td><td>{item.snapshot.comments??'Unavailable'}</td><td>{item.snapshot.shares??'Unavailable'}</td><td>{item.snapshot.favorites??'Unavailable'}</td><td>{item.snapshot.follower_delta??'Unavailable'}</td><td>{item.snapshot.source}{item.is_effective?'':' · corrected'}</td><td>{fmt(item.snapshot.created_at)}</td></tr>)}</tbody></table></div>}</>}</Panel>
 <Panel title="CSV Import · performance-csv-v1"><div className="notice">Choose File → Preview → Validation Summary → Confirm Apply。Preview 无副作用；有 validation error 时 Apply 禁用；Apply 是 all-or-nothing。</div><div className="actions"><button onClick={downloadTemplate}>Download CSV Template</button><input aria-label="Performance CSV file" type="file" accept=".csv,text/csv" onChange={e=>void chooseFile(e.target.files?.[0])}/><button disabled={!csvText} onClick={()=>void previewCsv()}>Preview</button><button disabled={!actorConfigured||!preview||preview.invalid_rows>0||preview.errors.length>0} onClick={()=>void applyCsv()}>Confirm Apply</button></div>{preview&&<><div className="metric-grid compact"><Metric label="Valid" value={preview.valid_rows}/><Metric label="Invalid" value={preview.invalid_rows}/><Metric label="Duplicate" value={preview.duplicate_rows}/><Metric label="Mapping" value={preview.mapping_version}/></div>{preview.errors.length>0&&<div className="table-wrap"><table><tbody>{preview.errors.slice(0,20).map((e,index)=><tr key={`${e.row_number}-${e.field}-${index}`}><td>row {e.row_number}</td><td>{e.field}</td><td>{e.code}</td><td>{e.message}</td></tr>)}</tbody></table></div>}</>}</Panel></div>
}
