import {useCallback,useEffect,useState} from 'react'
import {Drawer,Empty,ErrorBanner,ResourceHeader} from '../components/common'
import {Badge,Metric,fmt} from '../components/workbench'
import {decisionLabel,editorialFormatLabel,publicationModeLabel,sourceTypeLabel} from '../uiLabels'
import type {PublicationApi} from '../publicationApi'
import {publicationError} from '../publicationApi'
import type {PublicationListResponse,PublicationMode} from '../publicationTypes'
import type {WorkbenchApi} from '../workbenchApi'
import type {EditorialDraft,WorkbenchEventItem} from '../workbenchTypes'

export function PublicationsPage({api,workbench,actorConfigured,onOpenEvent}:{api:PublicationApi;workbench:WorkbenchApi;actorConfigured:boolean;onOpenEvent:(id:string)=>void}){
 const[data,setData]=useState<PublicationListResponse|null>(null),[events,setEvents]=useState<WorkbenchEventItem[]>([]),[drafts,setDrafts]=useState<EditorialDraft[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[recordOpen,setRecordOpen]=useState(false),[platformFilter,setPlatformFilter]=useState(''),[mode,setMode]=useState<PublicationMode>('workflow'),[eventId,setEventId]=useState(''),[draftId,setDraftId]=useState(''),[platform,setPlatform]=useState(''),[url,setUrl]=useState(''),[postId,setPostId]=useState(''),[account,setAccount]=useState(''),[publishedAt,setPublishedAt]=useState(''),[title,setTitle]=useState(''),[cover,setCover]=useState(''),[body,setBody]=useState(''),[reason,setReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[result,eventPage]=await Promise.all([api.publications({platform_key:platformFilter||undefined}),workbench.events({page:1,pageSize:50,includeMerged:false})]);setData(result);setEvents(eventPage.items)}catch(e){setError(publicationError(e))}finally{setLoading(false)}},[api,workbench,platformFilter]);useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!eventId){setDrafts([]);setDraftId('');return}void workbench.drafts(eventId).then(rows=>{setDrafts(rows);setDraftId(current=>rows.some(d=>d.id===current)?current:'')}).catch(e=>setError(publicationError(e)))},[eventId,workbench])
 const resetForm=()=>{setMode('workflow');setEventId('');setDraftId('');setPlatform(platformFilter);setUrl('');setPostId('');setAccount('');setPublishedAt('');setTitle('');setCover('');setBody('');setReason('')}
 const openRecord=()=>{resetForm();setError(null);setRecordOpen(true)}
 const canRecord=Boolean(actorConfigured&&eventId&&platform.trim()&&url.trim()&&publishedAt&&(mode==='manual_backfill'?reason.trim():draftId))
 const record=async()=>{if(!canRecord)return;setPending(true);setError(null);try{await api.record({event_id:eventId,draft_id:mode==='workflow'?draftId||null:null,publication_mode:mode,platform_key:platform.trim().toLowerCase(),account_label:account||null,external_post_id:postId||null,public_url:url,published_at:new Date(publishedAt).toISOString(),title_snapshot:title||null,cover_text_snapshot:cover||null,body_snapshot:body||null,backfill_reason:mode==='manual_backfill'?reason||null:null});setMessage('发布结果已记录。该记录只表示真实发布事实，不会自动向平台发送内容。');setRecordOpen(false);resetForm();await load()}catch(e){setError(publicationError(e))}finally{setPending(false)}}
 const prerequisite=!actorConfigured?'请先配置执行者 ID。':!eventId?'请选择事件。':!platform.trim()?'请填写发布平台。':!url.trim()?'请填写公开链接。':!publishedAt?'请选择发布时间。':mode==='workflow'&&!draftId?'工作流模式必须选择一个 Draft 版本。':mode==='manual_backfill'&&!reason.trim()?'手动补录必须填写补录原因。':''
 return <div className="operations-page publication-page">
  <ErrorBanner error={error}/>{message&&<div className="success-banner">{message}</div>}
  <section className="panel">
   <ResourceHeader title="发布记录" description="已采用不等于已发布。这里只登记已经真实发布的内容，并保留 Event、Draft 与人工判断快照。" actions={<><button onClick={()=>void load()}>刷新</button><button className="primary" onClick={openRecord}>记录发布结果</button></>}/>
   <div className="filter-bar"><label>平台筛选<input aria-label="Publication platform filter" value={platformFilter} onChange={e=>setPlatformFilter(e.target.value)} placeholder="输入平台标识"/></label></div>
   {loading&&<div className="section-state">正在加载发布记录…</div>}
   {!loading&&data?.items.length===0&&<Empty text="暂无发布记录" helper="真实内容发布后，在这里登记平台、链接、发布时间和对应 Draft。" action={<button className="primary" onClick={openRecord}>记录发布结果</button>}/>}
   {!loading&&data&&data.items.length>0&&data.items.map(item=>{const p=item.publication,s=item.latest_performance?.snapshot;return <article className="event-row" key={p.id}><div className="event-main"><button className="link-button event-title" onClick={()=>onOpenEvent(p.event_id)}>{item.event_title}</button><div className="badges"><Badge>{p.platform_key}</Badge><Badge>{publicationModeLabel[p.publication_mode]||p.publication_mode}</Badge>{p.candidate_rank_snapshot&&<Badge>候选 #{p.candidate_rank_snapshot}</Badge>}{p.editorial_decision_snapshot&&<Badge>人工：{decisionLabel[p.editorial_decision_snapshot]||p.editorial_decision_snapshot}</Badge>}</div><a href={p.public_url} target="_blank" rel="noreferrer">打开公开链接</a><small>发布于 {fmt(p.published_at)} · {p.draft_version_snapshot?`Draft v${p.draft_version_snapshot}`:'未绑定 Draft'}</small></div><div className="event-stats"><Metric label="播放量" value={s?.views??'暂无'}/><Metric label="完播率" value={s?.completion_rate!=null?`${(s.completion_rate*100).toFixed(1)}%`:'暂无'}/><Metric label="点赞数" value={s?.likes??'暂无'}/><Metric label="最近观察" value={s?fmt(s.observed_at):'暂无表现数据'}/></div></article>})}
  </section>

  <Drawer open={recordOpen} title="记录发布结果" description="这里只登记已经真实发布的结果，不会自动向任何平台发送内容。" width="wide" onClose={()=>{setRecordOpen(false);resetForm()}} footer={<><button disabled={pending} onClick={()=>{setRecordOpen(false);resetForm()}}>取消</button><button className="primary" disabled={pending||!canRecord} title={prerequisite} onClick={()=>void record()}>{pending?'正在记录…':'记录为已发布'}</button></>}>
   {!canRecord&&prerequisite&&<div className="prerequisite-hint">{prerequisite}</div>}
   <div className="drawer-section"><h3>内容来源</h3><p>工作流发布必须永久绑定 exact Draft 版本；手动补录不会伪造候选、人工决定或 Draft。</p><div className="form-grid"><label>记录方式<select aria-label="发布记录方式" value={mode} onChange={e=>setMode(e.target.value as PublicationMode)}><option value="workflow">工作流发布</option><option value="manual_backfill">手动补录</option></select></label><label className="field-full">事件<select aria-label="发布事件" value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">选择事件</option>{events.map(item=><option key={item.event.id} value={item.event.id}>{item.event.title}</option>)}</select></label>{mode==='workflow'&&<label className="field-full">使用的 Draft 版本<select aria-label="发布 Draft" value={draftId} onChange={e=>setDraftId(e.target.value)}><option value="">选择 Draft 版本</option>{drafts.map(d=><option key={d.id} value={d.id}>v{d.draft_version} · {sourceTypeLabel[d.source_type]||d.source_type} · {editorialFormatLabel[d.format_key]||d.format_key} · {fmt(d.created_at)}</option>)}</select></label>}{mode==='manual_backfill'&&<label className="field-full">补录原因<textarea aria-label="补录原因" value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明为什么需要历史补录"/></label>}</div></div>
   <div className="drawer-section"><h3>发布渠道</h3><p>填写平台侧可以被再次核对的账号、内容 ID、公开链接与发布时间。</p><div className="form-grid"><label>平台<input aria-label="发布平台" value={platform} onChange={e=>setPlatform(e.target.value)} placeholder="稳定平台标识，如 team.channel"/></label><label>发布账号<input aria-label="发布账号" value={account} onChange={e=>setAccount(e.target.value)}/></label><label>平台内容 ID<input aria-label="平台内容 ID" value={postId} onChange={e=>setPostId(e.target.value)}/></label><label>发布时间<input aria-label="发布时间" type="datetime-local" value={publishedAt} onChange={e=>setPublishedAt(e.target.value)}/></label><label className="field-full">公开链接<input aria-label="公开 URL" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label></div></div>
   <div className="drawer-section"><h3>最终发布内容</h3><p>这些字段用于保留发布时快照；正文没有单独快照需求时可以留空。</p><div className="form-grid"><label className="field-full">最终标题<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field-full">封面文案<textarea value={cover} onChange={e=>setCover(e.target.value)}/></label><label className="field-full">最终正文（可选）<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div></div>
  </Drawer>
 </div>
}
