import {useCallback,useEffect,useState} from 'react'
import {Empty,ErrorBanner,Panel} from '../components/common'
import {Badge,Metric,fmt} from '../components/workbench'
import {decisionLabel,editorialFormatLabel,publicationModeLabel,sourceTypeLabel} from '../uiLabels'
import type {PublicationApi} from '../publicationApi'
import {publicationError} from '../publicationApi'
import type {PublicationListResponse,PublicationMode} from '../publicationTypes'
import type {WorkbenchApi} from '../workbenchApi'
import type {EditorialDraft,WorkbenchEventItem} from '../workbenchTypes'

export function PublicationsPage({api,workbench,actorConfigured,onOpenEvent}:{api:PublicationApi;workbench:WorkbenchApi;actorConfigured:boolean;onOpenEvent:(id:string)=>void}){
 const[data,setData]=useState<PublicationListResponse|null>(null),[events,setEvents]=useState<WorkbenchEventItem[]>([]),[drafts,setDrafts]=useState<EditorialDraft[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[platform,setPlatform]=useState(''),[mode,setMode]=useState<PublicationMode>('workflow'),[eventId,setEventId]=useState(''),[draftId,setDraftId]=useState(''),[url,setUrl]=useState(''),[postId,setPostId]=useState(''),[account,setAccount]=useState(''),[publishedAt,setPublishedAt]=useState(''),[title,setTitle]=useState(''),[cover,setCover]=useState(''),[body,setBody]=useState(''),[reason,setReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[result,eventPage]=await Promise.all([api.publications({platform_key:platform||undefined}),workbench.events({page:1,pageSize:50,includeMerged:false})]);setData(result);setEvents(eventPage.items)}catch(e){setError(publicationError(e))}finally{setLoading(false)}},[api,workbench,platform]);useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!eventId){setDrafts([]);setDraftId('');return}void workbench.drafts(eventId).then(rows=>{setDrafts(rows);setDraftId(current=>rows.some(d=>d.id===current)?current:'')}).catch(e=>setError(publicationError(e)))},[eventId,workbench])
 const record=async()=>{setError(null);try{await api.record({event_id:eventId,draft_id:mode==='workflow'?draftId||null:null,publication_mode:mode,platform_key:platform,account_label:account||null,external_post_id:postId||null,public_url:url,published_at:new Date(publishedAt).toISOString(),title_snapshot:title||null,cover_text_snapshot:cover||null,body_snapshot:body||null,backfill_reason:mode==='manual_backfill'?reason||null:null});setUrl('');setPostId('');setReason('');await load()}catch(e){setError(publicationError(e))}}
 const canRecord=actorConfigured&&eventId&&platform.trim()&&url.trim()&&publishedAt&&(mode==='manual_backfill'?reason.trim():draftId)
 return <div className="event-list publication-page">
  <Panel title="发布" actions={<button onClick={()=>void load()}>刷新</button>}>
   <div className="page-intro"><p><strong>已采用不等于已发布。</strong>这里只记录已经真实发布的内容，不会自动向平台发送内容。</p></div>
   <div className="filter-bar"><label>平台筛选<input aria-label="Publication platform filter" value={platform} onChange={e=>setPlatform(e.target.value)} placeholder="输入平台标识"/></label></div>
   <ErrorBanner error={error}/>{loading&&<div className="section-state">正在加载发布记录…</div>}
   {!loading&&data?.items.length===0&&<Empty text="暂无发布记录"/>}
   {!loading&&data&&data.items.map(item=>{const p=item.publication,s=item.latest_performance?.snapshot;return <article className="event-row" key={p.id}><div className="event-main"><button className="link-button event-title" onClick={()=>onOpenEvent(p.event_id)}>{item.event_title}</button><div className="badges"><Badge>{p.platform_key}</Badge><Badge>{publicationModeLabel[p.publication_mode]||p.publication_mode}</Badge>{p.candidate_rank_snapshot&&<Badge>候选 #{p.candidate_rank_snapshot}</Badge>}{p.editorial_decision_snapshot&&<Badge>人工：{decisionLabel[p.editorial_decision_snapshot]||p.editorial_decision_snapshot}</Badge>}</div><a href={p.public_url} target="_blank" rel="noreferrer">打开公开链接</a><small>发布于 {fmt(p.published_at)} · {p.draft_version_snapshot?`Draft v${p.draft_version_snapshot}`:'未绑定 Draft'}</small></div><div className="event-stats"><Metric label="播放量" value={s?.views??'暂无'}/><Metric label="完播率" value={s?.completion_rate!=null?`${(s.completion_rate*100).toFixed(1)}%`:'暂无'}/><Metric label="点赞数" value={s?.likes??'暂无'}/><Metric label="最近观察" value={s?fmt(s.observed_at):'暂无表现数据'}/></div></article>})}
  </Panel>
  <Panel title="记录发布结果">
   <div className="notice">工作流记录会永久绑定所选 Draft 版本；手动补录不会伪造候选、编辑决定或 Draft。</div>
   <section className="form-section"><h3>内容来源</h3><div className="form-grid"><label>记录方式<select aria-label="发布记录方式" value={mode} onChange={e=>setMode(e.target.value as PublicationMode)}><option value="workflow">工作流发布</option><option value="manual_backfill">手动补录</option></select></label><label>事件<select aria-label="发布事件" value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">选择事件</option>{events.map(item=><option key={item.event.id} value={item.event.id}>{item.event.title}</option>)}</select></label>{mode==='workflow'&&<label>使用的 Draft 版本<select aria-label="发布 Draft" value={draftId} onChange={e=>setDraftId(e.target.value)}><option value="">选择 Draft 版本</option>{drafts.map(d=><option key={d.id} value={d.id}>版本 v{d.draft_version} · {sourceTypeLabel[d.source_type]||d.source_type} · {editorialFormatLabel[d.format_key]||d.format_key} · {fmt(d.created_at)}</option>)}</select></label>}{mode==='manual_backfill'&&<label>补录原因<textarea aria-label="补录原因" value={reason} onChange={e=>setReason(e.target.value)}/></label>}</div></section>
   <section className="form-section"><h3>发布渠道</h3><div className="form-grid"><label>平台<input aria-label="发布平台" value={platform} onChange={e=>setPlatform(e.target.value.toLowerCase())} placeholder="稳定平台标识，如 team.channel"/></label><label>发布账号<input aria-label="发布账号" value={account} onChange={e=>setAccount(e.target.value)}/></label><label>平台内容 ID<input aria-label="平台内容 ID" value={postId} onChange={e=>setPostId(e.target.value)}/></label><label>公开链接<input aria-label="公开 URL" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>发布时间<input aria-label="发布时间" type="datetime-local" value={publishedAt} onChange={e=>setPublishedAt(e.target.value)}/></label></div></section>
   <section className="form-section"><h3>最终内容</h3><div className="form-grid"><label>最终标题<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>封面文案<textarea value={cover} onChange={e=>setCover(e.target.value)}/></label><label>最终正文（可选）<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div></section>
   <button className="primary" disabled={!canRecord} onClick={()=>void record()}>记录为已发布</button>{!actorConfigured&&<small className="warning-text">配置 Actor ID 后才能记录发布结果。</small>}
  </Panel>
 </div>
}
