import {useCallback,useEffect,useState} from 'react'
import {Empty,ErrorBanner,Panel} from '../components/common'
import {Badge,Metric,fmt} from '../components/workbench'
import type {PublicationApi} from '../publicationApi'
import {publicationError} from '../publicationApi'
import type {PublicationListResponse,PublicationMode} from '../publicationTypes'
import type {WorkbenchApi} from '../workbenchApi'
import type {EditorialDraft,WorkbenchEventItem} from '../workbenchTypes'

export function PublicationsPage({api,workbench,actorConfigured,onOpenEvent}:{api:PublicationApi;workbench:WorkbenchApi;actorConfigured:boolean;onOpenEvent:(id:string)=>void}){
 const[data,setData]=useState<PublicationListResponse|null>(null),[events,setEvents]=useState<WorkbenchEventItem[]>([]),[drafts,setDrafts]=useState<EditorialDraft[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[platform,setPlatform]=useState(''),[mode,setMode]=useState<PublicationMode>('workflow'),[eventId,setEventId]=useState(''),[draftId,setDraftId]=useState(''),[url,setUrl]=useState(''),[postId,setPostId]=useState(''),[account,setAccount]=useState(''),[publishedAt,setPublishedAt]=useState(''),[title,setTitle]=useState(''),[cover,setCover]=useState(''),[body,setBody]=useState(''),[reason,setReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[result,eventPage]=await Promise.all([api.publications({platform_key:platform||undefined}),workbench.events({page:1,pageSize:50,includeMerged:false})]);setData(result);setEvents(eventPage.items)}catch(e){setError(publicationError(e))}finally{setLoading(false)}},[api,workbench,platform]);useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!eventId){setDrafts([]);setDraftId('');return}void workbench.drafts(eventId).then(rows=>{setDrafts(rows);setDraftId(current=>rows.some(d=>d.id===current)?current:'')}).catch(e=>setError(publicationError(e)))},[eventId,workbench])
 const record=async()=>{setError(null);try{await api.record({event_id:eventId,draft_id:mode==='workflow'?draftId||null:null,publication_mode:mode,platform_key:platform,account_label:account||null,external_post_id:postId||null,public_url:url,published_at:new Date(publishedAt).toISOString(),title_snapshot:title||null,cover_text_snapshot:cover||null,body_snapshot:body||null,backfill_reason:mode==='manual_backfill'?reason||null:null});setUrl('');setPostId('');setReason('');await load()}catch(e){setError(publicationError(e))}}
 const canRecord=actorConfigured&&eventId&&platform.trim()&&url.trim()&&publishedAt&&(mode==='manual_backfill'?reason.trim():draftId)
 return <div className="event-list"><Panel title="Publications" actions={<button onClick={()=>void load()}>Refresh</button>}><div className="notice"><strong>Publication ≠ Adopt ≠ Draft.</strong> 这里只记录实际发布结果，不会向平台发送内容。</div><label>Platform filter<input aria-label="Publication platform filter" value={platform} onChange={e=>setPlatform(e.target.value)}/></label><ErrorBanner error={error}/>{loading&&<div className="section-state">Loading Publications…</div>}{!loading&&data?.items.length===0&&<Empty text="No publications recorded"/>}{!loading&&data&&data.items.map(item=>{const p=item.publication,s=item.latest_performance?.snapshot;return <article className="event-row" key={p.id}><div className="event-main"><button className="link-button event-title" onClick={()=>onOpenEvent(p.event_id)}>{item.event_title}</button><div className="badges"><Badge>{p.platform_key}</Badge><Badge>{p.publication_mode}</Badge>{p.candidate_rank_snapshot&&<Badge>Rank #{p.candidate_rank_snapshot}</Badge>}{p.editorial_decision_snapshot&&<Badge>Human: {p.editorial_decision_snapshot}</Badge>}</div><a href={p.public_url} target="_blank" rel="noreferrer">Open recorded URL</a><small>Published {fmt(p.published_at)} · exact Draft {p.draft_version_snapshot?`v${p.draft_version_snapshot}`:'Unavailable'}</small></div><div className="event-stats"><Metric label="Views" value={s?.views??'Unavailable'}/><Metric label="Completion" value={s?.completion_rate!=null?`${(s.completion_rate*100).toFixed(1)}%`:'Unavailable'}/><Metric label="Likes" value={s?.likes??'Unavailable'}/><Metric label="Observed at" value={s?fmt(s.observed_at):'No performance data'}/></div></article>})}</Panel>
 <Panel title="Record Publication / 记录已发布内容"><div className="notice">这里只记录实际发布结果，不会向平台发送内容。workflow 将永久绑定所选 exact Draft version；manual_backfill 不会伪造 Candidate / Decision / Draft。</div><div className="filter-grid"><label>Mode<select aria-label="Publication mode" value={mode} onChange={e=>setMode(e.target.value as PublicationMode)}><option value="workflow">workflow</option><option value="manual_backfill">manual_backfill</option></select></label><label>Event<select aria-label="Publication Event" value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Select Event</option>{events.map(item=><option key={item.event.id} value={item.event.id}>{item.event.title}</option>)}</select></label>{mode==='workflow'&&<label>Exact Draft<select aria-label="Publication Draft" value={draftId} onChange={e=>setDraftId(e.target.value)}><option value="">Select Draft version</option>{drafts.map(d=><option key={d.id} value={d.id}>chain {d.draft_chain_id.slice(0,8)} · v{d.draft_version} · {d.source_type} · {d.format_key} · {fmt(d.created_at)}</option>)}</select></label>}<label>Platform<input aria-label="Publication platform" value={platform} onChange={e=>setPlatform(e.target.value.toLowerCase())} placeholder="stable key, e.g. team.channel"/></label><label>Account Label<input aria-label="Publication account label" value={account} onChange={e=>setAccount(e.target.value)}/></label><label>External Post ID<input aria-label="External post ID" value={postId} onChange={e=>setPostId(e.target.value)}/></label><label>Public URL<input aria-label="Public URL" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Published At<input aria-label="Published at" type="datetime-local" value={publishedAt} onChange={e=>setPublishedAt(e.target.value)}/></label>{mode==='manual_backfill'&&<label>Backfill reason<textarea aria-label="Backfill reason" value={reason} onChange={e=>setReason(e.target.value)}/></label>}<label>Final Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Cover Text<textarea value={cover} onChange={e=>setCover(e.target.value)}/></label><label>Final Body optional<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div>{mode==='workflow'&&draftId&&<div className="notice">Publication 将永久绑定此 Draft version。若最终标题/封面/正文留空，将从 exact Draft 确定性 snapshot。</div>}<button disabled={!canRecord} onClick={()=>void record()}>Record Publication / 记录已发布内容</button>{!actorConfigured&&<small className="warning-text">Configure Actor ID before recording.</small>}</Panel></div>
}
